### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by TaranPR** [tarampampam/random-user-agent#10]
## Steps to reproduce:
 1. Подменить ua
 2. https://whoer.net/ru
 3. UA и данные JS не соответствуют.

## Expected behaviour:
соответствовать

## Actual behaviour:
не соответствует

---------

### System information:
**Browser version**:
Google Chrome 55.0.2883.87 m

**Extension version**:

 2.1.0.1

**Comment by tarampampam** [comment]
Так как на ресурсе обработчик получения ua запускается во время загрузки страницы, а не по её завершению (это и есть как раз то самое ограничение, когда клиент определяет ua быстрее, чем запускается mock для его подмены) - данное расширение не может его подменить. Можно было бы запускать inject перед запуском клиентских скриптов, но в таком случае мы не сможем получить и подставить именно тот, который как раз надо подставить. Так же можно было бы предварительно его подменять на, например `N/A`, но тогда могут пострадать другие ресурсы, которые его используют для своей работы. В общем - ситуация довольно сложная, и на данный момент я не нашел её решения.

**Comment by TaranPR** [comment]
user-agent switcher for chrome делает это успешно, проверил, но не обладает
функционалом генерирования.

21 января 2017 г., 10:52 пользователь Paramtamtam <notifications@github.com>
написал:

**Comment by tarampampam** [comment]
Ссылку на него, пожалуйста?

**Comment by TaranPR** [comment]
Ознакомьтесь с приложением "User-Agent Switcher for Chrome":
https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg?utm_source=gmail

2017-01-21 16:47 GMT+03:00 Paramtamtam <notifications@github.com>:

**Comment by tarampampam** [comment]
Хм, приведенный вами в качестве примера плагин выполняет один запрос к бэкэнду против пяти у моего, хотя общая логика mock-а аналогична. Более того - мой не всегда отрабатывает не верно (т.е. проблема носит не постоянный характер), от чего я могу сделать что проблема кроется именно в этом. Я подумаю о том, как можно разрешить данную проблему (точнее уже знаю как это сделать, но руки пока не дойдут в ближайшие дни).

В любом случае - большое спасибо за ваш репорт. Очень прям здорово.

**Comment by TaranPR** [comment]
не за что

21 января 2017 г., 17:16 пользователь Paramtamtam <notifications@github.com>
написал:

**Comment by tarampampam** [comment]
Опубликовал в store патченную версию. Проверяйте.
