### ISSUE TITLE
Settings are being forgetten on private mode

### ISSUE THREAD

**Issue by undergroundwires** [tarampampam/random-user-agent#100]
## Describe the bug
Settings are not being carried in private sessions

### Expected behaviour:

My settings work in every private session

### Actual behaviour:

Settings (domain rules) are not following through private sessions of Firefox.

### Steps to reproduce the behavior:

 1. Configure Firefox to always start in private mode
 2. Go to a webpage, disable "enabled on this domain" or save a manual rule
 3. Restart Firefox

### Desktop (please complete the following information):

- OS: Windows
- Browser: Firefox
- Version: 66.0.2 (64-bit)

**Comment by neroux** [comment]
Probably related to #56 and #90

If you disable the browser sync it should work.

**Comment by undergroundwires** [comment]
I set `webextensions.storage.sync.enabled` to false [as described](https://github.com/tarampampam/random-user-agent/issues/90#issuecomment-451773017) and now it works. I never wanted sync anyway. Thanks for very fast help!
