### ISSUE TITLE
System information

### ISSUE THREAD

**Issue by macxpedia** [tarampampam/random-user-agent#101]
Good day. You have done a greet job. But there is an issue, I would like you to work on. The system information was detected, when I tried it on some browser web detection site. Eg the operating system was detected. You can try ipleak.net. Thanks, and keep up the good work

**Comment by neroux** [comment]
That is most likely related to #7.

**Comment by macxpedia** [comment]
Thanks not really what bargain for, but you just  gave a clue on how one can work things around. In my own opinion,we should not rely on user-agent alone, but some little tweaks from a browser. Thanks bro. We might work on something new.
