### ISSUE TITLE
Protect against detection by Javacript (experimental)

### ISSUE THREAD

**Issue by 377573684** [tarampampam/random-user-agent#103]
Protect against detection by Javacript (experimental)

![1](https://user-images.githubusercontent.com/49289992/56850581-28321780-6937-11e9-9536-13ac68b5c0f8.png)

![2](https://user-images.githubusercontent.com/49289992/56850584-33854300-6937-11e9-875a-f029f915c9d6.png)

Chrome has turned this feature on. The website (www.zhihu.com) is still detected to open the Random-user-agent and cannot use some functions of the website (www.zhihu.com).

**Comment by neroux** [comment]
Please dont double post but continue in #102
