### ISSUE TITLE
Mousewheel zoom not working on maps.yandex.ru [Firefox]

### ISSUE THREAD

**Issue by ramuxuyem** [tarampampam/random-user-agent#105]
_Sounds silly? I also did not believe in it at first._

I use Random User-Agent 2.2.10 on Firefox.

- When I open [maps.yandex.ru](https://maps.yandex.ru) and try to change the scale of the map with the mouse wheel — no reaction.
- Incognito mode is not affected.
- If I turned off the extension for this domain (the icon turns gray) and refresh the page — no reaction.
- If I turned off the extension completely in the firefox settings and refresh the page — everything works perfectly.

I tried to determine the cause on my own (may be add-on blocks javascript event or script), but I could't. I don't see any errors in the browser console

### System information
- OS: Windows
- Browser: Firefox
- Version: 67.0.2 64 bit

**Comment by neroux** [comment]
Not silly at all, rather good old browser sniffing I am afraid.
https://github.com/tarampampam/random-user-agent/issues?q=label%3A%22Browser+sniffing%22

Yandex appears to return different content based on the reported user agent.

The reason why whitelisting did not work is that it only adds the main domain to the list. In this case Yandex loads additional JavaScript content from other domains as well, which wont be covered by the whitelisting.

Additionally to the - already - whitelisted `http?://yandex.com/*` entry, you'd also need to add the following

    http?://api-maps.yandex.ru/*
