### ISSUE TITLE
Random User-Agent  detect and the site blocks 

### ISSUE THREAD

**Issue by TiPoTa95** [tarampampam/random-user-agent#106]
I really like Random User-Agent 
I can not use the Random User-Agent on a site it is often detect and the site blocks me I would like to know the different settings to be more efficient with.

Thank you for your reply

**Comment by neroux** [comment]
Which site is it? But it simply might be [browser sniffing](https://github.com/tarampampam/random-user-agent/issues?q=label%3A%22Browser+sniffing%22).

**Comment by TiPoTa95** [comment]
It is the site leboncoin.com, sometimes it works with the software random-user-agent and sometimes the site blocks me and sends me a captcha.

**Comment by neroux** [comment]
In that case it might be some sort of security layer, but that is not necessarily user agent specific. Could be also IP or cookie related. If you find a clear way to reproduce it, it could be further analysed.

**Comment by neroux** [comment]
@TiPoTa95, closing this for the time being. If you can provide further information which points to an actual issue with the extension, which is not browser sniffing, please post a follow up.

**Comment by TiPoTa95** [comment]
hello sorry for the response time I made a very big sprained foot

No it does not come from cookies or IP

I do not know how the site detects Random User-Agent

**Comment by neroux** [comment]
Without further information I am afraid it is impossible to say what is happening.

**Comment by TiPoTa95** [comment]
Hello
Thank you for your answer, what information do you need?

**Comment by neroux** [comment]
You'd need to debug the issue and report back the findings and what the site might be doing.
