### ISSUE TITLE
not updated some user agent

### ISSUE THREAD

**Issue by elvin143** [tarampampam/random-user-agent#107]
microsoft edge, safari mac, xbox, is not updated, try to use spotify.com you got error browser is not supported

**Comment by neroux** [comment]
Xbox uses the same version as Edge and Edge is on the most recent version. It does go back to version 15 though, so you might have to refresh the user agent if that version is not accepted.

As far as Safari is concerned, I'd ask you to submit a pull request with an updated version. You can find it at https://github.com/tarampampam/random-user-agent/blob/master/extension/js/UAGenerator.js#L91
