### ISSUE TITLE
Limit range of random numbers/seperators for OS string

### ISSUE THREAD

**Issue by zh2eou** [tarampampam/random-user-agent#11]
I'm noticing that for some values being generated, the range of it goes out of the realm of realistic values. For example, if I have a Mac platform selected, the value for the OS version can show up as "Intel Mac OS X 10_19_2" which is not a real version, or it may end up as a really old version which doesn't match a relatively new browser version. 

Also for Mac platforms, it doesn't seem to take into account what type browser is being used for the OS string. Firefox uses dots as separators ("Intel Mac OS X 10.11") while Chrome/Safari uses underscores ("Intel Mac OS X 10_11_6"). 

Fixing these inconsistencies would result would help in masking some really obvious fake UA settings.

**Comment by neroux** [comment]
Valid concerns :+1:.

Considering this issue, coupled with #13, maybe it would be a good idea to move from the current system to a (maintained) list of fixed user agents, similar to what adblockers do.

**Comment by tarampampam** [comment]
Mmmmmmmaybe.. :D But not right now, dude, sorry

**Comment by neroux** [comment]
@zh2eou #22 should address that. At least the first issue, the different separators might be trickier

**Comment by neroux** [comment]
@zh2eou 82ea3a8 should now fix the issue with different separators under different browsers.
