### ISSUE TITLE
Lost your User-Agent list

### ISSUE THREAD

**Issue by roman82101** [tarampampam/random-user-agent#114]
Hello, when adding a list from https://olegon.ru/showthread.php?t=31713
and then restarting the Google Chrome browser Version 80.0.3987.106 (Official Assembly), (64 bit) the list disappears on Deepin 15.11 (64 bit)

**Comment by neroux** [comment]
Try disabling the data sync in the settings. It appears Chrome only allows up to 100 KB of data in that context and your list is larger than 300 KB.

**Comment by roman82101** [comment]
Thank you helped
