### ISSUE TITLE
Update of browser versions

### ISSUE THREAD

**Issue by neroux** [tarampampam/random-user-agent#13]
Is there a plan as to how to keep the reported version numbers up-to-date (apart from regular code updates)?

RUA is using for Firefox the versions 50 to 55 and we are currently at 53 for the release and 55 for the nightly, so for the time being it is still not that much of a problem.

For Chrome the situation is already a bit trickier as RUA uses 56 to 58 and we are already at 58 for the release version. The nightly is already at version 60. Furthermore, RUA uses x.x.2xxx as subversion while Chrome switched to 3xxx as of 58.

**Comment by shenanigans12** [comment]
This is a huge problem, 90% of the websites I visit either load to a blank page, or prevent access stating that I'm using an "out of date" or "incompatible" browser.  Almost every browser option triggers these warnings, including something as generic as "Chrome on Windows."  Its been a problem for weeks but today its completely unusable.

**Comment by tarampampam** [comment]
Now is ok? :)

**Comment by neroux** [comment]
@shenanigans12 Would you have some sample websites? While the issue should be addressed in the near future, I would still not call it a "huge problem".

@tarampampam Thanks for the new version, though something appears to have gone wrong, every install attempt (be it an update or a fresh extension installation after removal) results in a brief appearance of RAS in the extension list only to be immediately deactivated with a "This extension may have been corrupted." message. Did the signing fail maybe? Browser is the developer channel v60.

**Comment by tarampampam** [comment]
IDK, dude, I checked this right now - uninstalled first, and install RAS from chrome web stole - and all is ok. Maybe some troubles with extensions cache inside browser? Can you try on another browser instance (portable, using virtual machine or anything else)?

Chrome version: Версия 58.0.3029.96 (64-bit)
OS: Debian family

**Comment by neroux** [comment]
I'll try it later in a virtual machine'd installation but could you also try it meanwhile with version 60.

The issue seems to be most likely related to the signature and was also reported at https://github.com/EFForg/https-everywhere/issues/5874 (turned out to be an issue with Chrome, https://bugs.chromium.org/p/chromium/issues/detail?id=643814#c11 - hence knowing whether you'd have the issue with 60 as well could indicated if its possibly an issue with the new Chrome version).

I'll try also clearing everything cache-ish as suggested under https://github.com/EFForg/https-everywhere/issues/5874#issuecomment-244624330.

**Comment by tarampampam** [comment]
Ok, I will waiting for your report. A cannot not install chrome v60 for this, sorry.

**Comment by neroux** [comment]
I removed everything even remotely related to caching and the issue is still there. If you cant confirm that it doesnt happen with you on v60 I'd assume for the time being that there is some signing issue with the new version on the latest Chrome version.

As I mentioned, I'll try later to check whether I can reproduce it on v58 too.

**Comment by neroux** [comment]
I opened a separate issue (#15) for the sake of clarity and am closing this one as the versions were updated with the latest update.

**Comment by shenanigans12** [comment]
@neroux I didn't mean to raise alarm but it is a complete blocker, particularly for banking websites. Examples that would not load at all (i.e. Blank white page, no message of any kind) include usbank.com and Barclaycardus.com. I haven't been keeping track but I would say the majority of the finance related sites that I visit (bank accounts, credit cards, etc) are impacted by this extension

**Comment by neroux** [comment]
@shenanigans12 The only the page where I had the **impression** that whitelisting was necessary was Paypal ("impression" because I cant confirm the necessity), but even there I had no blank pages or similar. Did you whitelist the sites?

**Comment by shenanigans12** [comment]
Ah good point, these are the sites I've had to whitelist to get them to load properly:

http?://www.capitalone.com/*
http?://www4.usbank.com/*
http?://rewards.usbank.com/*
http?://www.americanexpress.com/*
http?://secure03b.chase.com/*
http?://www.cbsnews.com/*
http?://www.linkedin.com/*
http?://www.glassdoor.com/*
http?://navient.com/*
http?://www.aviatormastercard.com/*
http?://payroll.intuit.com/*
http?://www.schwab.com/*
http?://online.citi.com/*

As you can see, almost exclusively banking/finance sites

**Comment by neroux** [comment]
I dont have accounts with them, so I cant tell what happens behind the login, however I could load these sites with altered user agents without problems. Are you sure it is the extension and not something else?

Also, have you enabled the Javascript override? Even though possibly unlikely they might try to match the reported user agent against [what the navigator object returns](https://www.w3schools.com/jsref/obj_navigator.asp).

**Comment by shenanigans12** [comment]
I have enabled "Protection against detection by Javascript" do you recommend disabling that feature?

Also, I guess other extensions could be contributing, but whitelisting seems to resolve the problem.

**Comment by neroux** [comment]
No, no that option should be enabled to cover earlier mentioned possibility of a match of the user agent against the JS values.

**Comment by neroux** [comment]
@shenanigans12 One potential problem might be the invalid Windows version numbers but that should be fixed with #17
