### ISSUE TITLE
 version 2.2.13 bugs ?

### ISSUE THREAD

**Issue by wanglai8** [tarampampam/random-user-agent#133]
it show useragent firefox 83 and 86

![ff83](https://user-images.githubusercontent.com/53934936/87842701-9f572100-c8d8-11ea-9a78-02d3ebe0c814.png)

![ff86](https://user-images.githubusercontent.com/53934936/87842705-a41bd500-c8d8-11ea-8197-2fce8be8ac44.png)

**Comment by tarampampam** [comment]
Latest firefox versions is:

![Screenshot (1)](https://user-images.githubusercontent.com/7326800/87852958-c9800180-c91f-11ea-9b83-bd84499758f0.png)

So, `83` seems is ok, but `86` is not - did you mean it?

**Comment by wanglai8** [comment]
its my bad, i think RUA should show until lastest relesad version FF 78.x

**Comment by jorik392** [comment]
@tarampampam

The new update includes Firefox versions that do not exist yet. It should only go up to version 81.
