### ISSUE TITLE
Provide the extension for Thunderbird

### ISSUE THREAD

**Issue by Kreyren** [tarampampam/random-user-agent#135]

**Comment by Kreyren** [comment]
FWIW it seems to already work when installed manually.

![image](https://user-images.githubusercontent.com/11302521/89796578-1b383800-db2a-11ea-8523-b773634d58a7.png)

**Comment by Kreyren** [comment]
FWIW the `general.useragent.override` works in my thunderbird

**Comment by tarampampam** [comment]
Sorry, but not now. When I will have enough free time for this project (`v3` already started in this repository) - we will talk about this again, ok?

**Comment by tarampampam** [comment]
Can you check now, please?
