### ISSUE TITLE
Buy Extension

### ISSUE THREAD

**Issue by ryanfishman90** [tarampampam/random-user-agent#141]
Hello,
are you interested about to sell your Random User-Agent Webstore extension? Can you please contact me via mail? lordsword88 @ gmail . com

Thank you :)

**Comment by JakeTrock** [comment]
it's open source. You don't need to pay for it as long as you follow the lisence

**Comment by jessefogarty** [comment]
he probably wants to buy the existing user base and access to their site permissions.
