### ISSUE TITLE
Chrome refuses to load RUA

### ISSUE THREAD

**Issue by neroux** [tarampampam/random-user-agent#15]
## Steps to reproduce:
 1. Install the extension under Chrome 59+

## Expected behaviour:
The extension should be loaded by Chrome.

## Actual behaviour:
The extension gets briefly loaded only to fail with the following message

![image](https://cloud.githubusercontent.com/assets/24754773/25707769/d570e2b0-30e4-11e7-8408-87dc63b9293b.png)

Other extensions had similar issues (https://github.com/EFForg/https-everywhere/issues/5874) when the signature check failed.

Neither removing and re-installing the extension nor clearing all possible caches helped.

---------

### System information:
**Browser version**: Chrome 60.0.3080.6 dev (64-bit)

**Extension version**: 2.1.4 (2.1.3 loaded fine)

**Console screenshot**: N/A

**Comment by neroux** [comment]
I can now confirm that it works under v58, but it doesnt as of v59 (the current beta).

**Comment by neroux** [comment]
2.1.5 has fixed the issue.

**Comment by tarampampam** [comment]
Great thx 2 u
