### ISSUE TITLE
А problem with сustom UA

### ISSUE THREAD

**Issue by kentawr** [tarampampam/random-user-agent#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Custom UA disappear after a new start of the browser.
Yesterday after the update it was fine, but today there is a bug in version 3.2.0.

### Browser

Chrome

### Extension version

3.2.0

**Comment by kentawr** [comment]
Console is empty: https://i2.paste.pics/EKP16.png

Two more wishes.

1. In this version with each change of UA the page reboots.
Sometimes must to change many UA, and after each  updated the site.

2. I have a dark theme in my browser.
Now there is almost nothing visible:

https://i2.paste.pics/EKP36.png

And in the old version it was clearly visible.

**Comment by tarampampam** [comment]
@kentawr В качестве исключения давай по-русски :) Скриншот консоли нужно делать тогда, когда что-то не работает (в твоем случае, как понимаю - не сохраняются/загружаются кастомные UA). Пока нет ни логов, ни возможности воспроизвести ошибку - её невозможно исправить, к сожалению.

По отображению тёмный темы - воспроизвёл, спасибо большое! Но на будущее, пожалуйста, один issue для какого одного конкретного кейса (для чего-то вне топика - отдельные issue следует создавать), иначе разобраться в них потом просто невозможно.

**Comment by kentawr** [comment]
Отлично! 8)

Значит, вот скрин: https://i2.paste.pics/EL18U.png
Насколько я понял, слово "quota" говорит о превышении количества UA. Я там вбил штук двести примерно, но до двух последних апдейтов вбивал весь имеющийся набор, там примерно три сотни, и всё работало.

Выше прочёл твой коммент другому юзеру по поводу альтернативы встроенного генератора UA пользовательским юзер-агентам. А сколько возможных вариантов у встроенного генератора? По прошлым версиям помню, что  немного; у меня для трёх браузеров на базе Windows получалось что-то в районе двух десятков, этого мало.

И насчёт перезагрузки сайта после каждой смены UA тоже подумай. Потому что я не вебмастер, я использую RUA, как одно из вспомогательных средств для цифровой гигиены, скажем так. И получается, что пока я переберу энное кол-во вариантов, страница, на которой я нахожусь, перезагрузится столько же раз. Для вебмастеров и пр. программеров это удобно, для обычного же пользования наоборот. 
Чтобы все были довольны, может, добавить опцию в настройках, чтобы у каждого был выбор, если это возможно, конечно?

По поводу "один вопрос - один issue" понял, я тут редкий гость, не знал.

**Comment by Urszak** [comment]
From what I see I have a similar problem to the author, all custom UAs have been removed. Every time I relaunch the browser I have to add them again. 

As I understand it, it has to do with limiting the number of UAs that can be saved? 
With the previous version of the plugin I didn't observe such an error, the deletion of custom UAs took place only when synchronization between browsers was enabled.

**Comment by tarampampam** [comment]
@kentawr Please, check now. A new release has been published recently!

**Comment by tarampampam** [comment]
@kentawr все ли хорошо после обновления?
