### ISSUE TITLE
Update the lowest allowed version for macOS

### ISSUE THREAD

**Issue by KazamaSion** [tarampampam/random-user-agent#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

"macOS 10.12" now can be generated as part of UA. But Blackboard, which is used by my school for online teaching, only allows the 10.14+ macOS users to use their services.
https://help.blackboard.com/Collaborate/Ultra/Moderator/Get_Started/Browser_Support#certified-browsers-and-operating-systems_OTP-1

### Browser

Chrome

### Anything else?

Actually, I should submit it as a feature request. If there's a feature that allows users to set the version range which can be generated.

**Comment by tarampampam** [comment]
Hi @KazamaSion!

Only the latest versions generation will reduce the randomization. Maybe you can add the blackboard domain to the ignore list?

**Comment by KazamaSion** [comment]
> Hi @KazamaSion!
> 
> Only the latest versions generation will reduce the randomization. Maybe you can add the blackboard domain to the ignore list?


I'm actually using 3.2.0. But I solve it by disabling macOS in the randomization list. 
Just suggesting that you can allow users to set the version range to avoid similar issues by adding a new feature. You decide if you want to close this issue or not.
Thanks.
