### ISSUE TITLE
Protection against detecting the "true" operating system?

### ISSUE THREAD

**Issue by tarampampam** [tarampampam/random-user-agent#191]
### Discussed in https://github.com/tarampampam/random-user-agent/discussions/188

<div type='discussions-op-text'>

<sup>Originally posted by **curiosityseeker** November  7, 2021</sup>
Thank you for your useful add-on!

I've noticed that on some test sites the "true" operating system is detected. For example on:

https://www.deviceinfo.me/

which reports my faked OS as "Mac OS X version 11.3.6 (32-bit)" but detects my correct OS as "Linux x86_64".

Similarly on 

https://browserleaks.com/javascript

where the platform navigator object is reported as "MacIntel" but the oscpu is again recognized as "Linux x86_64".

I wonder if something can be done against this?</div>

**Comment by tarampampam** [comment]
Cannot be reproduced

**Comment by curiosityseeker** [comment]
Well, here are sceenshots that show what I'm talking about:
Output of https://www.deviceinfo.me/
![grafik](https://user-images.githubusercontent.com/60518106/141333782-fc9cff49-3d1a-49bf-a435-a96559bee887.png)
Output of https://browserleaks.com/javascript
![grafik](https://user-images.githubusercontent.com/60518106/141334023-d7b0c155-a40d-4517-b285-27a8922ba21c.png)

In `General settings` the first 4 are enabled, in `Generator settings` Firefox on Windows, Mac and Linux are enabled.

What am I missing?

**Comment by tarampampam** [comment]
Your browser & os :)

**Comment by curiosityseeker** [comment]
Firefox 94.0.1 on Arch Linux.

**Comment by tarampampam** [comment]
The problem is confirmed. The [fixed release (v3.3.1)](https://github.com/tarampampam/random-user-agent/releases/tag/v3.3.1) has been published. Great thanks for your report! :+1:

**Comment by curiosityseeker** [comment]
@tarampampam : Cool - thank you very much! I can confirm that this fix also works for me. Great work :)
