### ISSUE TITLE
Doesn't hide "Ture OS Core" anymore.

### ISSUE THREAD

**Issue by Rexadev** [tarampampam/random-user-agent#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using deviceinfo.me, previous versions could hide it.

### Browser

Chrome

### Extension version

3.3.1

**Comment by tarampampam** [comment]
This is **not** my real UA. All seems working fine, how I can reproduce your problem?

![image](https://user-images.githubusercontent.com/7326800/142993919-36dbb587-e5be-4a3c-8204-427933680e60.png)

**Comment by Rexadev** [comment]
> Hi @Rexadev! This is **not** my real OS. All seems working fine, how I can reproduce your problem?
 
I reinstalled the extension and now it's working. But sometimes it just doesn't hide true OS Core.

**Comment by tarampampam** [comment]
Please, comment again when described behavior will be reproducible. Closing for now
