### ISSUE TITLE
window.navigator.userAgent reveals true User Agent

### ISSUE THREAD

**Issue by wasaylor** [tarampampam/random-user-agent#23]
## Steps to reproduce:
 1. Open Chrome developer console
 2. observe the return value of window.navigator.userAgent

## Expected behaviour:
Tell us what should happen

window.navigator.userAgent return value should match the extensions User Agent

## Actual behaviour:
Tell us what happens instead

window.navigator.userAgent return value is the true browser User Agent. I am explicitly testing this on pages I do not have whitelisted in Random User Agent settings.

---------

### System information:
**Browser version**:
```
Version 60.0.3112.78 (Official Build) (64-bit)
```

**Extension version**:
```
2.1.7
```

**Console screenshot**:
> **Menu > Settings > More tools > Extensions > Developer mode (check) > Random User-Agent > Background Page**

![Console screenshot](https://cloud.githubusercontent.com/assets/7326800/17556647/98b7f4dc-5f2d-11e6-9eeb-ca2f3dd8e541.png)

**Comment by neroux** [comment]
Can you name a site where you encounter the issue? Or could it be related to #24?

**Comment by wasaylor** [comment]
@neroux Hi, I have tested it on various sites including GitHub. I checked "Verbose" in chrome log levels, and I'm seeing this message from your extension:

`[Random User-Agent] User-Agent JavaScript protection disabled!`

**Comment by neroux** [comment]
Well, that message would indicate that you havent enabled that feature. You'd need to do so in the settings.

**Comment by wasaylor** [comment]
You're right, totally missed that. Is it enabled by default? Anyway, now getting this error message:

`content.js:1 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`

So I think I'm running into #24

**Comment by neroux** [comment]
[By default it is disabled](https://github.com/tarampampam/random-user-agent/blob/master/extension/js/Settings.js#L38)

And yes, unfortunately you are running into #24 in this particular case - and there's also #26

**Comment by neroux** [comment]
@wasaylor The issue #24 should be fixed now, once @tarampampam publishes a new version it should be available publicly.

**Comment by neroux** [comment]
@wasaylor Should be fixed now.
