### ISSUE TITLE
Spoof CSS @supports(-*webkit-app-region: inherit) { .selector { } }

### ISSUE THREAD

**Issue by Rexadev** [tarampampam/random-user-agent#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Go to https://noscriptfingerprint.com/
Then More Detail
It can tell browser using CSS

### Suggest a solution

-

### Additional context

-

**Comment by tarampampam** [comment]
This extension is designed to hide the real user-agent and not the browser. There are various "leaks", and you can try to use another extension for "fixing" them.
