### ISSUE TITLE
Add user-defined rules by regexp

### ISSUE THREAD

**Issue by stoned-meth-addicted-alcoholic** [tarampampam/random-user-agent#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Add user-defined rules by regexp (optional), for expirieced users.

### Suggest a solution

So, instead of two rules
```
http?://domain.com/*
http?://*.domain.com/*
```
user could just add smth like
```
/^https?:\/\/(?:[^\/]+?\.)?domain\.com\//
```
So, if rule starts and ends with "/" - it's regarded as RegExp.

**Comment by grobpidor** [comment]
U can do this just like:
js/background.js:
```
...
        function b(e, t) {
          const r = (t.startsWith("/") && t.endsWith("/")) ? t.slice(1, -1) : t.replace(/[[\]{}()+.\\^$|]/g, "\\$&")
            .replace(/[*?]/g, ".$&");
          return new RegExp(`^${r}$`, "i")
            .test(e)
        }
...
```

**Comment by tarampampam** [comment]
I don't want to do that, thanks for your suggestion

**Comment by stoned-meth-addicted-alcoholic** [comment]
But this won't be worth the trouble for u, and may be convenient for someone. Opportunities * and ? is not enough for some purposes, as is the 2048 characters length for the exclusion list.
