### ISSUE TITLE
Provide a global keyboard shorcut to get new user-agent

### ISSUE THREAD

**Issue by stoned-meth-addicted-alcoholic** [tarampampam/random-user-agent#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Provide a global keyboard shorcut to get new user-agent.

### Suggest a solution

But do not show the popup after changing - cause Esc press should be needed. Better show notification for, for example, 5sec - not more. Thnx.

**Comment by tarampampam** [comment]
Hi @stoned-meth-addicted-alcoholic! Is that request still actual for you?

**Comment by tarampampam** [comment]
Keyboard shortcut to user-agent renewal implemented and will be released soon. Thanks for your issue!

**Comment by tarampampam** [comment]
Released in [v3.12.0](https://github.com/tarampampam/random-user-agent/releases/tag/v3.12.0)
