### ISSUE TITLE
Whitelist doesn't seem to be working

### ISSUE THREAD

**Issue by pogue** [tarampampam/random-user-agent#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes when I visit a website, it will not function properly because I have Random User Agent (RUA) on, so I go under my whitelist and add the domain to the whitelist. I save the settings, and reload the page but still get the same result. So, I have to go under extensions and disable RUA in order for it to work. I'm not sure if I'm using the correct parameters to whitelist the page (for example, using https:// or http?://, putting asterisks where they need to be and so forth.)

I don't know if I can somehow provide a log or anything of this behavior to help troubleshoot it. I am using many other extensions, but this one in particular is the one that causes me the most problems.

![random_browser_ext_bug2](https://user-images.githubusercontent.com/5632678/164456787-126ae175-d530-4126-87d5-1d45e07935d3.png)
![random_browser_ext_bug](https://user-images.githubusercontent.com/5632678/164456789-c130821a-ff15-44cf-9399-c1949bfb287b.png)

### Steps to reproduce

1. Visit a website (some websites have no problem with RUA - while others do not work. This morning I was having trouble with Reddit)
2. Attempt to load the page and see that it's not loading correctly nor functionating properly.
3. Go under RUA options and whitelist the site
4. Reload the page
5. No change has occurred - sometimes at this point I will attempt to clear the cookies from the website to make sure that's not the problem, but it never is
6. Disable RUA in order to access the page properly

### Browser

Opera

### Extension version

3.7.0

**Comment by stoned-meth-addicted-alcoholic** [comment]
Only domain names allowed in domain list, not URL patterns,
U should use URL patterns in Custom rules.
Personally, I edited the plugin code and using regex there, because the author apparently does not care.

**Comment by pogue** [comment]
> Only domain names allowed in domain list, not URL patterns, U should use URL patterns in Custom rules. Like this: https://prnt.sc/dsCC-SDcQkS0 Personally, I edited the plugin code and using regex there, because the author apparently does not care. This code is checking domain, just literal correspondence of a domain name:
> 
> ```
>           enabledForDomain(e) {
>             const t = this.settings.get()
>               .blacklist.domains;
>             switch (this.settings.get()
>               .blacklist.mode) {
>             case c.OM.BlackList:
>               return !t.includes(e);
>             case c.OM.WhiteList:
>               return t.includes(e)
>             }
> ```
> 
> And this is code for URL patterns:
> 
> ```
>         function b(e, t) {
>           const r = t.replace(/[[\]{}()+.\\^$|]/g, "\\$&")
>             .replace(/[*?]/g, ".$&");
>           return new RegExp(`^${r}$`, "i")
>             .test(e)
>         }
> ```
> 
> ? as .? and * as .* in regexp.
> 
> Also, if u interested, i am using this extension https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search to define custom user agent 4 sites that breaks with RUA. Cloudflare usually breaks, voice IM like discord, meet.jit.si, etc. So, sites that do not work with random ua, works with fake value anyway. Just set site to exclusion list in RUA and set up fake value in UA switcher via custom mode (in JSON format).

Well, that would explain a lot!! Because in the instructions it clearly says to use http, etc. Are you planning on making your plugin for Chromium/Blink? Because I'm a diehard Opera user and don't want to switch.

**Comment by stoned-meth-addicted-alcoholic** [comment]
> Are you planning on making your plugin for [Chromium/Blink](https://Chromium/Blink)?

I'm not the author, I'm just a user who edits the code of used plugins when i need to, with extension signature verification disabled on FF Beta/DevEdition. I don't plan to make a plugin even for FF, too lazy to maintain and all this crap, sorry =)

**Comment by tarampampam** [comment]
The blacklist has been redesigned a bit (and one error was fixed), check the latest release, please 🥳
