### ISSUE TITLE
EN locale bugz

### ISSUE THREAD

**Issue by tarampampam** [tarampampam/random-user-agent#3]
@SmudgedMuffin - can you check [this file](https://github.com/tarampampam/random-user-agent/blob/master/_locales/README.md)? All is correct?

**Comment by SmudgedMuffin** [comment]
Will get to work on this now.

**Comment by tarampampam** [comment]
Looks great, thx again

**Comment by SmudgedMuffin** [comment]
Anytime! Happy to help
