### ISSUE TITLE
Support for Firefox 57+

### ISSUE THREAD

**Issue by gegemon2012** [tarampampam/random-user-agent#30]
Hello!
As is known since firefox 57 it will go to webextension and then many plugins will stop working. I tried to adapt your plug-in via Chrome store foxified but it does not work although the settings menu opens regularly. Do you plan to adapt your plug-in for firefox?

**Comment by neroux** [comment]
One of the reasons why it doesnt work will be the use of the chrome.* namespace, [whereas Firefox and Edge use the generic browser.* namespace](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities).

**Comment by RichBron** [comment]
Dear @tarampampam , how I can contact you? I have a collaborative suggestion :) can you please write your e-mail or Skype?

**Comment by pupyc** [comment]
We hope you have time to do so, because there is no user agent switcher for firefox compatible with firefox 57+, or at least I didn't see it!

**Comment by neroux** [comment]
@RichBron Is this related to the Firefox port? If not, please open another issue.

@gegemon2012 @pupyc I havent fully tested it yet, but it might be that #32 just fixed the Firefox incompatibility.

**Comment by neroux** [comment]
@gegemon2012 @pupyc I ran a few more tests, still not extensively though, and it seems RUA works fine now in Firefox. If you want to test it yourself you can use https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/ to install it.

**Comment by neroux** [comment]
Apart from the minor visual glitch fixed by 0055e72 RUA seems to work now just fine in Firefox. Do you have any plans to publish it on Mozilla's site as well @tarampampam?

**Comment by tarampampam** [comment]
@neroux dude, say to me your email, and I will add you to the chrome developers dashboars. As you can see - I have no free time now for opensource projects :(

**Comment by tarampampam** [comment]
@neroux dude?

**Comment by neroux** [comment]
@tarampampam I hope you did get the notification with the address

**Comment by neroux** [comment]
@gegemon2012 @pupyc Did you manage to test it and could you provide some feedback?

**Comment by neroux** [comment]
A first experimental version has been published at https://addons.mozilla.org/firefox/addon/random_user_agent/
