### ISSUE TITLE
Firefox 56.0.2

### ISSUE THREAD

**Issue by DekaSKy** [tarampampam/random-user-agent#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Не работает контекстное меню на firefox 56.0.2 в следствии не заменяет юзерагент
![image](https://user-images.githubusercontent.com/77372383/168427648-4e84ae9d-2a65-4017-8634-428aea5b218a.png)

### Browser

Firefox 56.0.2

### Extension version

3.7.0

**Comment by tarampampam** [comment]
Please, attach the extension logs

**Comment by DekaSKy** [comment]
> Please, attach the extension logs

Where can i find this log?

**Comment by tarampampam** [comment]
I have checked on my side - in the latest firefox, all works fine. Please, update your browser.
