### ISSUE TITLE
Enhancement: show gray icon if disabled on current tab

### ISSUE THREAD

**Issue by iki** [tarampampam/random-user-agent#31]

**Comment by neroux** [comment]
Not a bad idea, there is a grey icon already (which however indicates the entire extension is disabled), so I'd suggest to use a light grey / transparent for being disabled and the current icon for being disabled on the current page.

Any comments @tarampampam?

**Comment by neroux** [comment]
@iki #33 should address this

**Comment by neroux** [comment]
@iki That feature should be available now
