### ISSUE TITLE
Support URL regex for Whitelist

### ISSUE THREAD

**Issue by fakhamatia** [tarampampam/random-user-agent#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Please add support URL regex for Whitelist
 like this:
`(10)(\.([2]([0-5][0-5]|[01234][6-9])|[1][0-9][0-9]|[1-9][0-9]|[0-9])){3}`
`(172)\.(1[6-9]|2[0-9]|3[0-1])(\.(2[0-4][0-9]|25[0-5]|[1][0-9][0-9]|[1-9][0-9]|[0-9])){2}`
`(192)\.(168)(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])){2}`

**Comment by tarampampam** [comment]
Hi and thanks for your issue! But what problem does it solve? You can use custom rules with wildcards, and I suppose - this is the easiest way to manage rules for users, who don't know how to use regular expressions (that's why wildcards are used instead of regular expressions).

**Comment by tarampampam** [comment]
The custom rules were removed in v4.0.0 (due to the browser API limitation for MV3), so I need to close this issue. Sorry for the inconvenience :(
