### ISSUE TITLE
"Sec-CH-UA-Full-Version-List" is not processed by the extension

### ISSUE THREAD

**Issue by xcodejoy** [tarampampam/random-user-agent#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

HTTP header "Sec-CH-UA-Full-Version-List" is not processed by the extension.

Steps to reproduce:
1. Set User Agent to: "Mozilla/5.0 (Linux; Android 4.3; Nexus 7 Build/JSS15Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.1234.55 Safari/537.36"
2. Check HTTP header "Sec-CH-UA-Full-Version-List". It still contains (my browser): "Not;A=Brand";v="99.0.0.0", "Chromium";v="106.0.5249.91"

### Suggest a solution

HTTP header "Sec-CH-UA-Full-Version-List" must be changed.
Also a good idea to give ability to change HTTP header "Sec-CH-UA-Mobile".

**Comment by tarampampam** [comment]
Hi Volodymyr! Thanks for your issue, I will implement additional headers faking shortly.

**Comment by tarampampam** [comment]
I have released version [3.10.0](https://github.com/tarampampam/random-user-agent/releases/tag/v3.10.0). Feel free to close this issue after checking on your side :)

**Comment by tarampampam** [comment]
Ping @xcodejoy

**Comment by tarampampam** [comment]
Closed due inactivity

**Comment by xcodejoy** [comment]
GREAT! Many thanks!
