### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by neroux** [tarampampam/random-user-agent#35]
Hi @tarampampam,

there have been [quite a few changes since 2.1.7](https://github.com/tarampampam/random-user-agent/compare/9911dcb...4033171) and I guess it would be nice to have 2.1.8 :)

**Comment by tarampampam** [comment]
@neroux - Just now make a new release - `2.1.8`. All is ok now? ;)

And sorry for a delay, dude

**Comment by neroux** [comment]
Thanks.

**Comment by neroux** [comment]
@tarampampam Regarding your question in #30 .... the address would be _[github-username]_ at gmail dot com

I am going to remove this message, I hope you'll get the notification
