### ISSUE TITLE
User-agent Client Hints antidetect

### ISSUE THREAD

**Issue by eltempo** [tarampampam/random-user-agent#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

When the Random User-Agent is enabled [browserleaks.com/client-hints](https://browserleaks.com/client-hints) shows the real User-agent of the browser Chromium 108 Win10 in the lines User Agent Client Hints JavaScript API:
![Chromium108+RandomUser-Agent](https://user-images.githubusercontent.com/115508229/195134460-11e249a6-db0b-45ca-8984-e7ccbed2092c.jpg)

### Suggest a solution

This is solved by the [User-Agent Switcher and Manager extension](https://github.com/ray-lothian/UserAgent-Switcher/) has other flaws
![Chromium108+User-AgentSwitcherandManager](https://user-images.githubusercontent.com/115508229/195136457-30ef8afd-6ab6-4c9a-a585-2bf14de07d5f.jpg)

### Additional context

Since Chrome 101 Google dropped the User-agent and [move toward User-Agent Client Hints](https://developer.chrome.com/blog/user-agent-reduction-deprecation-trial/)
so it might be worth paying attention to the fake Client Hints value

**Comment by tarampampam** [comment]
Hi @eltempo and thanks for your issue! I will make an attempt to fix this 👍🏼

**Comment by tarampampam** [comment]
🔥 I have released version [3.11.0](https://github.com/tarampampam/random-user-agent/releases/tag/v3.11.0). Feel free to close this issue after checking on your side :)

**Comment by tarampampam** [comment]
You made this extension better, thank you!
