### ISSUE TITLE
🙏🏼 Need help localizing this extension

### ISSUE THREAD

**Issue by tarampampam** [tarampampam/random-user-agent#353]
Since this extension is used by more than 200,000 users on the Chrome Web Store, help is needed to translate it into the following languages:

- [ ] Korean (`ko`)
- [x] Indonesian (`id`)
- [ ] Chinese (Taiwan) (`zh_TW`)
- [ ] Vietnamese (`vi`, _automatic translation errors need to be fixed_)
- [x] French (`fr`)
- [ ] Japanese (`ja`)
- [ ] Spanish (`es`)
- [ ] Polish (`pl`)
- [ ] Turkish (`tr`)
- [ ] Dutch (`nl`)
- [ ] Italian (`it`)
- [ ] Ukrainian (`uk`)

If someone can help with this, I (and other users) would be very grateful 👍🏼 

> The localization process is described ➡️ [here](https://github.com/tarampampam/random-user-agent/blob/master/public/_locales/readme.md)

### Additional context

Here are the user stats, grouped by locale. And a visualization.

![Screenshot](https://user-images.githubusercontent.com/7326800/195796814-3094ea5f-ac39-483e-80a3-3cdce9510f57.png)

[CSV file (14 oct 2022)](https://github.com/tarampampam/random-user-agent/files/9783863/list.csv)

**Comment by tarampampam** [comment]
@xcodejoy could you help with the Ukrainian locale, please?

**Comment by tarampampam** [comment]
@maxgfr can I ask you to help with the French?

**Comment by tarampampam** [comment]
@py7hon Could you maybe spare some time and help with the Indonesian translation?

**Comment by Hvgcgctctx** [comment]
Have you ever tried to use https://weblate.org/?
It will be more convenient.

**Comment by tarampampam** [comment]
> Have you ever tried to use https://weblate.org/?
> It will be more convenient.

It doesn't have a free plan 😒

**Comment by Yctxtctx** [comment]
> > Have you ever tried to use https://weblate.org/?
> > It will be more convenient.
> 
> It doesn't have a free plan 😒

You are wrong:)
![7E86930C-0242-4412-B49C-721BE95F4A67](https://user-images.githubusercontent.com/120200229/206759679-3c71fe8b-826d-4d57-a867-2ca35b0d6bc5.jpeg)
![62FA40F0-9FA1-4181-A6B6-221B1BB9ADC0](https://user-images.githubusercontent.com/120200229/206759691-1690196f-a0c5-4980-b26a-d9f3de33e143.jpeg)

**Comment by Yctxtctx** [comment]
Also can you add Polish language?

**Comment by webact1** [comment]
Sent you two translations. Hope it will help you

**Comment by tarampampam** [comment]
@webact1 Thanks a lot!

**Comment by webact1** [comment]
> @webact1 Thanks a lot!

I sent you two more translations. I will try to translate the food into several languages, if possible:)

**Comment by tarampampam** [comment]
I'm very sorry, but automatic translation is always not as good as we would like it to be. This is the wrong way, and only native speakers' translations are welcome 😞

**Comment by tarampampam** [comment]
Ty for the link
