### ISSUE TITLE
Toggle for Black\White-List and Pause\Resume Switcher are linked

### ISSUE THREAD

**Issue by BrutuZ** [tarampampam/random-user-agent#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When switching the filtering mode to blacklist it pauses the switcher, when you resume the switcher it toggles the filtering mode to whitelist

### Steps to reproduce

1. Have Switcher Resumed and Filtering on Whitelist
2. Pause Switcher
3. Filtering mode is now on Blacklist
4. Toggle Filtering mode to Whitelist
5. Switcher is now resumed

### Browser

Firefox

### Extension version

3.14.2

**Comment by tarampampam** [comment]
Hi @BrutuZ! Bug confirmed, the fix will be made shortly, thank you!

**Comment by tarampampam** [comment]
I have made all the required changes, and the fix will be published in the closest release 👍🏼

**Comment by tarampampam** [comment]
@BrutuZ released in [v3.15.0](https://github.com/tarampampam/random-user-agent/releases/tag/v3.15.0)
