### ISSUE TITLE
как прописать свой User-Agent

### ISSUE THREAD

**Issue by seniord1** [tarampampam/random-user-agent#39]
## Steps to reproduce:
 1.
 2.
 3.

## Expected behaviour:
Tell us what should happen

## Actual behaviour:
Tell us what happens instead

---------

### System information:
**Browser version**:
```
For example: Google Chrome "52.0.2743.116 m", stable channel
```

**Extension version**:
```bash
For example: 2.0.1
```

**Console screenshot**:
> **Menu > Settings > More tools > Extensions > Developer mode (check) > Random User-Agent > Background Page**

![Console screenshot](https://cloud.githubusercontent.com/assets/7326800/17556647/98b7f4dc-5f2d-11e6-9eeb-ca2f3dd8e541.png)

**Comment by seniord1** [comment]
подскажите как прописать свой User-Agent

**Comment by tarampampam** [comment]
Настройки -> Свой User-Agent.

**Comment by seniord1** [comment]
что именно туда надо вписать?вписывал вот так(Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5)не получается,показывает настоящий.

**Comment by neroux** [comment]
You also need to enable it.

**Comment by seniord1** [comment]
именно так я и делал,ничего не получается выходит настоящий

**Comment by neroux** [comment]
If possible write in English please, a translation might not always be accurate.

I presume you wrote that you already tried that, correct? Can you take a screenshot of your settings? If you set the custom agent string and enabled it with the switch it should work.

**Comment by seniord1** [comment]
write an example of how to enter, can I not have entered?
I put so
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5

**Comment by neroux** [comment]
Hmm, I just tried it with the same user agent and it did work.

You are using version 2.1.10, right? Could you maybe try it from scratch again and remove the custom string, switch it off, maybe restart the browser (to be on the safe side) and enter the string again and then switch it on?

**Comment by neroux** [comment]
Alternatively, maybe try to uninstall and reinstall the extension. I realise that is an "[have you tried turning it off and on again](https://www.youtube.com/watch?v=nn2FB1P_Mn8)" solution but maybe a fix if the previous suggestion still does not work.

**Comment by seniord1** [comment]
Yes, I'm using 2.1.10 reinstalled,disconnected and again included no changes.I use the slimjet browser,can extension it does not work?

**Comment by neroux** [comment]
Thats a good point, the browser could very well be the reason.

**Comment by seniord1** [comment]
the reason was the browser?

**Comment by neroux** [comment]
Is that a statement or a question?

If the latter, I am afraid I cant say as I am not using that browser. I could possibly test it later today but I cant promise that yet. Could you maybe try it with Chrome itself too?

**Comment by neroux** [comment]
And another question, do the randomly generated user agents work?

**Comment by seniord1** [comment]
if directly in a browser, enter it does not work.I'm using portable slimjet browser,as it's not one and it's the only browser that can work regardless if to run another.I tried to run operaportable but if you run two browsers Opera the second which runs for some reason everything opens as the first.so I prefer to use the slimjet browser.

**Comment by seniord1** [comment]
portable slimjet browser is very convenient and quite docile.

**Comment by neroux** [comment]
I wasnt referring to when you manually enter an agent string but if you have it disabled and use the default randomised agent strings. Does this work?

As for Slimjet, you dont need to justify why you are using it :), it is just that I am not using it, and hence I cant test it at the moment. It appears to be based on Chrome, so in theory it should work .... in theory :)

As I mentioned, maybe I'll be able to test it on Slimjet later today, though I cant promise it yet. If so I'll get back to you.

**Comment by seniord1** [comment]
renomirani of extensions don't work only works if you insert your.

**Comment by neroux** [comment]
I am sorry, I didnt get that bit. I read it as random agents dont work and it only works with your own custom one. But this is obviously not the case, as the custom one does not work.

Considering that the last screenshot shows it as Firefox 55 I would assume you meant that random agent do actually work. Is that right?

**Comment by neroux** [comment]
I am afraid I cant reproduce it on Slimjet either. I just ran their latest version, 16.0.9.0 based on Chrome 61, and the custom user agent worked as supposed.

Are you running the latest version? Maybe try a new profile.

**Comment by neroux** [comment]
@seniord1 Has this been resolved for you?
