### ISSUE TITLE
Mobile browser support

### ISSUE THREAD

**Issue by ghost** [tarampampam/random-user-agent#392]
Hello!
I am one of the users of your extension! I ask you to port it for the mobile version of Firefox for Android as well. I really miss the possibility of installing your extension for the latest mobile version of the browser :(

**Comment by tarampampam** [comment]
Hey! Could you provide more information about it? Kinda docs or something like that?

**Comment by Ctxtctxrx** [comment]
Of course!

[Article about extensions for Android](https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android)

[Article about extension that can be installed on Android](https://support.mozilla.org/en-US/kb/recommended-extensions-program)

[Useful information](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) that works on Nightly version and [Fennec version](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/)

**Comment by tarampampam** [comment]
As I can see, all you need is a collection ID to install the addon into your mobile firefox:

![image](https://user-images.githubusercontent.com/7326800/205586504-46fa353c-919c-4322-8e5e-d5e6047089a6.png) ![image](https://user-images.githubusercontent.com/7326800/205586527-3183f72e-a3da-49f1-915d-438bb04541e2.png)

Enter `14112060` / `rua`.

After you tap “OK,” the application will close and restart. Is this enough for you?

**Comment by Hvhcyctfyg** [comment]
Thank you! It worked!

**Comment by tarampampam** [comment]
Glad to hear that! The issue can be closed, or I should describe this in the readme file?

**Comment by Crxrctcgc** [comment]
I think you should describe it in readme. Thank you for your help and work!

**Comment by Gyfycycgc** [comment]
Hello!
That’s me again! Hope I’m not annoying you.

I fouund this string in Firefox developer hub:
![97FF02D3-E468-468D-90A2-EFDA858ACB70](https://user-images.githubusercontent.com/119872792/205665893-a82a6225-c73f-4ea7-bb40-6182e9ef2dd4.jpeg)

it is opening after this steps:
![D2BA48DC-BC57-4034-8C55-328BC06C28F7](https://user-images.githubusercontent.com/119872792/205666034-d2734baa-866d-4217-b71c-2b0cd66ab96a.jpeg)
![5C3AB3DB-780C-475C-BEAB-8A44B808E137](https://user-images.githubusercontent.com/119872792/205666054-f41f928f-5c1a-4f46-9abc-6b567f590fb3.jpeg)

Hope this will or useful for you:)

**Comment by tarampampam** [comment]
During each release I have this checkbox checked :)
