### ISSUE TITLE
Cannot get custom whitelist rules to activate

### ISSUE THREAD

**Issue by balaji-dutt** [tarampampam/random-user-agent#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to change the user agent for certain websites only to Chrome while using the standard User Agent for most websites. I've tried to define the rules as mentioned in the Extension Options but it does not seem to be working.

I'm not sure if this is a factor of using both Multi-Account Containers & Temporary Containers addons but I will mention the steps I'm following

### Steps to reproduce

1. Install  Firefox Multi-Account Containers (v8.0.9) and Temporary Containers (v1.9.2)
2. Set Temporary Containers to "Automatic Mode"
3. Install Random User Agent (RUA)
4. Set RUA>Options>Generator to only activate "Chrome on Windows"
5. Change RUA>Options>Blacklist settings to "Whitelist mode" and add `*singaporeair.com` to the Custom rules. Clear out all entries in Domain names section
6. Navigate to www.singaporeair.com. Check Developer Tools>Network>Disable Cache. Reload the site. Then go to Developer Tools>Console and enter `window.navigator.userAgent `. The user agent will show `Firefox`.

### Browser

Chrome

### Extension version

3.16.1

**Comment by tarampampam** [comment]
Hi @balaji-dutt! The domain names list doesn't allow wildcards. You have 2 options - set `singaporeair.com` in the **domains list** or `chrome://*singaporeair.com` in the __custom rules__. I hope, this will help you.

**Comment by balaji-dutt** [comment]
> Hi @balaji-dutt! The domain names list doesn't allow wildcards. You have 2 options - set `singaporeair.com` in the **domains list** or `http?://*singaporeair.com` in the **custom rules**. I hope, this will help you.

Hi @tarampampam unfortunately `http?://*singaporeair.com` does not seem to work either. Screenshot of Blacklist settings below:

![firefox_16asJIWZwP](https://user-images.githubusercontent.com/3147070/207486196-d900aac7-4da4-4b60-b0dd-c1c0fb364460.png)

Screenshot of `https://www.singaporeair.com` with Developer Tools>Network showing that the User Agent is still Firefox 107 and not Chrome:

![Ca8VNiGSsa](https://user-images.githubusercontent.com/3147070/207486464-7581aa02-9614-40ec-9ea2-789f4114867c.jpg)

**Comment by balaji-dutt** [comment]
My basic tests seem to suggest the Custom rules don't work correctly right now. I tried the following:

- Switched to blacklist mode.
- Added `*google.com` to the Custom rules section
- Navigated to `google.com`

When I check the Developer Tools, I can see that even for `google.com`, the User Agent is set to `Chrome/109.0.5387.208 Safari/537.36` even though as per the Custom rules it should still show Firefox.

**Comment by tarampampam** [comment]
The custom rules were removed in v4.0.0 (due to the browser API limitation for MV3), so I need to close this issue. Sorry for the inconvenience :(
