### ISSUE TITLE
Some youtube pages are not loaded completely when the plugin is active

### ISSUE THREAD

**Issue by acritum** [tarampampam/random-user-agent#41]
#I used this plugin during 2 days and noticed that sometimes youtube video pages are not loaded completely when the plugin is active. This doesn't happen all the time, but quite often. Reloading the page doesn't help, but switching off "enabled for this domain" and then reloading it helps and the page loads completely. This is quite inconvenient, I think. When the problem occurs, I see only the top part of the page with youtube logo, and nothing loads at the bottom, no matter how many times I reload the page (F5), but switching the plugin off helps to reload the page completely.

Firefox 57/Windows7

**Comment by neroux** [comment]
This is most likely not a bug in the extension but due to browser sniffing on the side of the website, which presumably behaves differently for different browsers and whose "path" chosen for non-Firefox browsers will break on Firefox.

Can you post under which user agents Youtube fails to load? Also, try to (temporarily, as I wouldnt recommend to have it off permanently) switch off the JavaScript override in the configuration and check whether it makes a difference.

**Comment by neroux** [comment]
I seem to be able to reproduce the error. It happens when RUA is making the browser pose as Chrome, under which Youtube will try to call `document.registerElement` and [this function is not supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement).

Your best bet is probably to keep the original user agent for Youtube (switching off the Enabled toggle) or alternatively deselect Chrome from the list of user agents.

**Comment by neroux** [comment]
@acritum Has this been resolved for you?

**Comment by acritum** [comment]
In fact, I want to switch user agent randomly especially for google. They want to know too much about us all and I don't like it. I see that I am tracked by the kind of content that I see, although I'm not logged in in any google services. It looks like I need to delete cookies after every page load or switch IP randomly as well to be treated as a new unknown user, otherwise switching UA only seems to be useless. As far as the problem is concerned, I haven't tried it yet because I don't spend too much time in internet, Next time I go to youtube I'll set Firefox UAs only and let you know will it work or not. By the way, can you write a plugin that deletes cookies by wildcard on every exit? I tried to find such solutions but all plugins allow to keep cookies by exceptions, and I want to delete *google*, *yandex.ru, *mail.ru and some other tracking cookies of large corporations by a simple button click and on every exit and keep all the rest cookies of other websites. It would be also cool to have a button "delete cookies for this website" in the tool panel of  the browser for quick access.

**Comment by neroux** [comment]
Alright, yes please let me know when you know more. You could also try selecting other browsers in the browser list and check if it works. as mentioned though Chrome wont work regardless of the platform as Youtube sends content in that case that is only supported by Chrome.

As for your cookie question, maybe check out these three

* https://chrome.google.com/webstore/detail/auto-history-wipe/hdgnienkeomlaeeojaibeicglpoaadnj
* https://chrome.google.com/webstore/detail/cookie-autodelete/fhcgjolkccmbidfldomjliifgaodjagh
* https://chrome.google.com/webstore/detail/self-destroying-cookies/ghgghhceppfhemlgffnlbpaobcclhfdf

**Comment by acritum** [comment]
I have tested it during some time. Not sure, but it seems that it's not the Chrome, but OS selection is too blame. When UA points to Mac or even Linux, youtube pages load incompletely, but when it is Windows, it loads completely, even if Chrome is set as a browser. I didn't have much time for testing but all Mac browsers including even Firefox seem to result in incomplete page load. Selecting only Windows browsers seems to work fine, but it  still needs more testing to be sure (it also shows warnings for some "old" browsers and it has different view for mobile browsers but it is predictable).

Cookies: So far I haven't seen a good cookie plugin. They want to delete all or delete all except some domains, but I need to delete some domains and keep all the rest. Besides, I don't want to use Chrome. Although it's faster than Firefox, but it's from Google. I used to trace the connections that it makes on background and decided that I'd rather use slower Firefox than this spyware from google...

**Comment by neroux** [comment]
Thanks for the feedback. My tests show for some reason a slightly different picture*) but as long as we can rule out a bug in the extension our job here is done :).

About the cookies, sorry my bad for the Chrome links, I have replaced them with their Firefox counterparts.

---
*) Youtube fails for Blink-based browsers (Chrome and Opera) with the `document.registerElement is not a function` error but loads fine everywhere else.
