### ISSUE TITLE
Firefox version in Random User-Agent string haven't release

### ISSUE THREAD

**Issue by tomac4t** [tarampampam/random-user-agent#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to "Firefox Release Calendar" (https://wiki.mozilla.org/index.php?title=Release_Management/Calendar), **Firefox Night 111** will release in Jan 2023. 

But Random User-Agent can generate a lot of strings which Firefox versions are not exist:
![2023-01-03](https://user-images.githubusercontent.com/47532693/210256919-607f0556-cb93-4a03-a9ce-e7ff0376ed91.png)

Example strings:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20000101 Firefox/123.0
Mozilla/5.0 (Windows NT 11.0; Win64; rv:117.0) Gecko/20100101 Firefox/117.0/JnIgu2QvmF9Qhog-05
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20010101 Firefox/122.0
Mozilla/5.0 (Windows NT 11.0; Win64; x64; rv:116.0) Gecko/20100101 Firefox/116.0/5ubIYOk4f-40
```

~(Honestly, I was confused because these Firefox versions didn't release.)~

Edited:

I believe the author is misleading by Wikipedia, and that "Firefox version history" article not only has history versions but also future versions:
https://github.com/tarampampam/random-user-agent/blob/ecdf6e306c76cf95a2a41cd624b85fd1bb4ad83e/src/useragent/versions.ts#L44-L50

***
~I also check Chrome's random user-agent strings with https://omahaproxy.appspot.com/.~
Random User-Agent: `Chrome/110.0.5359.175`, ~Chrome dev: `110.0.5478.4`. Seems~ Random UA doesn't exist either: https://chromium.googlesource.com/chromium/src/+refs I believe Chromium's build and patch version is a fixed number, not random:

>  https://www.chromium.org/developers/version-numbers/
> Chromium version numbers consist of 4 parts: MAJOR.MINOR.BUILD.PATCH.
>    - MAJOR and MINOR may get updated with any significant Google Chrome release (Beta or Stable update). MAJOR must get updated for any backwards incompatible user data change (since this data survives updates).
>    - BUILD must get updated whenever a release candidate is built from the current trunk (at least weekly for Dev channel release candidates). The BUILD number is an ever-increasing number representing a point in time of the Chromium trunk.
>    - PATCH must get updated whenever a release candidate is built from the BUILD branch. [...]

The Good news is Chrome redacted the Chrome version in UA like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36`. It happens since Chrome 101:

> Chrome 101 protects user privacy by reducing the granularity of information in the User-Agent string. The MINOR.BUILD.PATCH version info in UA has been reduced to 0.0.0. You can control this using the UserAgentReduction enterprise policy. You can test the new reduced-granularity User-Agent string by setting the policy to 2, or you can delay the change while you update your apps by setting it to 1. 
> https://www.askvg.com/google-chrome-90-and-later-versions-changelog/

> Phase 4: Chrome 101
> CTA: Ensure your site is compatible with the reduced Chrome version number, and [migrate to UA Client Hints](https://web.dev/migrate-to-ua-ch/) if not.
> Ship reduced Chrome MINOR.BUILD.PATCH version numbers (“0.0.0”). Once rolled-out, the reduced UA string would apply to all page loads on desktop and mobile operating systems for sites that do not opt into the deprecation trial.
> https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

### Browser

Firefox

### Extension version

3.16.1

**Comment by tarampampam** [comment]
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently (here is the [link](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0)). Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿
