### ISSUE TITLE
URL with custom user-agents list

### ISSUE THREAD

**Issue by mazbron** [tarampampam/random-user-agent#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have test with 100 lines ualist.txt, but it not change user agent from URL on start, I must hit "Get ne agent" to get new UA from list.
Pls fix this.

Thanks

### Browser

Chrome

### Extension version

108

**Comment by tarampampam** [comment]
https://github.com/tarampampam/random-user-agent/blob/c6328cb9ca71e4e1ab13e0b2f3d53f3fb6e91c0e/README.md?plain=1#L63-L81

**Comment by mazbron** [comment]
> https://github.com/tarampampam/random-user-agent/blob/c6328cb9ca71e4e1ab13e0b2f3d53f3fb6e91c0e/README.md?plain=1#L63-L81

Hi,
Yep, I mean already using external host, https://mydomain.com/ualist.txt
But UA not change browser on start.

Thanks
