### ISSUE TITLE
Addon is adding a base64 encoded cookie to outbound requests

### ISSUE THREAD

**Issue by GH-A-CC** [tarampampam/random-user-agent#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/47477239/213758854-980ff7e5-5f34-43d6-a737-51b32b5ba211.png)

The value decodes to:
`{"uaInfo":{"useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_2_1; rv:110.0) Gecko/20000101 Firefox/110.0","engine":"gecko","osType":"macOS","browser":"firefox","browserVersion":{"major":110,"full":"110.0"}}}`  

Which is what the addon had set as my useragent.

If I toggle "enabled on this domain" to OFF, this cookie is not appended.

### Steps to reproduce

Install plugin.
Visit site were plugin is enabled.
Observe added cookie.

### Browser

Firefox

### Extension version

3.16.1

**Comment by tarampampam** [comment]
This is not a bug, this is a required condition for the extension to working

**Comment by tarampampam** [comment]
But anyway, thanks for your time and research!
