### ISSUE TITLE
Paypal bug

### ISSUE THREAD

**Issue by JustToReport123222** [tarampampam/random-user-agent#43]
Being on profile setting, when ever you click on setting's "update" button, it loads a page, displays it but after 1/2 or 1/4 of a second, it throws a blank white page. 
This happens only some setting.
For example, My settings > My checkout settings > update = blank page.

**Comment by neroux** [comment]
That is most likely a similar issue at #41 and hence there is unfortunately not much the extension can do (it is a bug with the site). Best solution would be whitelisting.
