### ISSUE TITLE
Защита от определения User-Agent'а Javascript'ом

### ISSUE THREAD

**Issue by astatium135** [tarampampam/random-user-agent#44]
Подскажите, пожалуйста, как вы реализовали защиту от определения User-Agent средствами JavaScript. Я в Вашем коде нашёл лишь requestHeaders'ы, но они устанавливают лишь отправляемый User-Agent.

**Comment by tarampampam** [comment]
https://github.com/tarampampam/random-user-agent/blob/master/extension/js/inject/content.js + https://github.com/tarampampam/random-user-agent/blob/master/extension/manifest.json

**Comment by astatium135** [comment]
Спасибо.
