### ISSUE TITLE
Can't download Windows 10 ISO when the extension is on

### ISSUE THREAD

**Issue by blanchyy** [tarampampam/random-user-agent#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As stated in the title—extension is preventing the ISO from being downloaded.

### Steps to reproduce

1. Go to https://www.microsoft.com/xxx/software-download/windows10ISO
2. Generate an ISO
3. Get an error message

### Browser

Firefox

### Extension version

3.17.0

### Anything else?

![image](https://user-images.githubusercontent.com/131486417/233713193-022cc718-66df-4e69-9edb-f642a4146978.png)

**Comment by tarampampam** [comment]
Can't reproduce


https://user-images.githubusercontent.com/7326800/233909871-c0086a03-ee74-4511-adcc-c9b0c2df9472.mp4
