### ISSUE TITLE
Extension not working with chrome headless on Ubuntu

### ISSUE THREAD

**Issue by gordon3636** [tarampampam/random-user-agent#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, Thanks to the author for creating a great extension. 

I get an error when I launch headless chrome using puppeteer on Ubuntu. The extension is pushed in and appears, but the browser doesn't recognize the new User agent.

Looking forward to your support. Thank you very much.

### Steps to reproduce

import {join} from "path";
import puppeteer from "puppeteer";

const pathToExtension = join(process.cwd(), "uragent");

const options = {
  headless: true,
  args: [
    `--disable-extensions-except=${pathToExtension}`,
    `--load-extension=${pathToExtension}`,
  ],
};

const browser = await puppeteer.launch(options);
const page = await browser.newPage();

await page.goto("https://google.com", {
  waitUntil: "networkidle0",
});

const ua = await page.evaluate(() => navigator.userAgent);
console.log("UA", ua);
await browser.close();

### Browser

Chrome

### Extension version

3.1.0

### Anything else?

![image](https://user-images.githubusercontent.com/131520795/233773814-e2005b4d-95ef-4e30-81c4-81a986ef146e.png)

**Comment by tarampampam** [comment]
As I can see, you opened the console not on the target page. Could you do the same but on page, opened using puppeteer?

**Comment by tarampampam** [comment]
Closed due inactivity
