### ISSUE TITLE
Adding custom user agents

### ISSUE THREAD

**Issue by quangthienit158** [tarampampam/random-user-agent#46]
Hi .. How can we add a new user agent? I want to add newer chrome versions like "Mozilla / 5.0 (Macintosh, Apple Mac OS X 10_13_2) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 62.0.3202.75 Safari / 537.36" from. and only use the user agent in the txt file. [UAE.txt](https://github.com/tarampampam/random-user-agent/files/1642036/UAE.txt)

**Comment by neroux** [comment]
In which browser are your currently using RUA?

**Comment by quangthienit158** [comment]
I use Chrome for WINDOWS

**Comment by neroux** [comment]
I am afraid in that case you can only specify one single custom user agent for now. The new version does come with support for a list of user agents but it has been published so far only for Firefox. Maybe you can give @tarampampam a little nudge and he will publish it for Chrome :).

**Comment by quangthienit158** [comment]
I used firefox
thank you very much

**Comment by quangthienit158** [comment]
Some sites identify as bot after I use it
![untitlederro](https://user-images.githubusercontent.com/35558281/35108439-2997022e-fca6-11e7-8af9-c0e95c56f9fa.png)

**Comment by neroux** [comment]
The screenshot you posted seems to be fine. Did you make sure you also enabled the JavaScript override in the settings?
