### ISSUE TITLE
README doesn't communicate fingerprinting danger introduced by this extension

### ISSUE THREAD

**Issue by strugee** [tarampampam/random-user-agent#47]
See https://github.com/nylira/prism-break/issues/1862#issuecomment-357900509 (although note that I'm not filing this with my PRISM Break contributor hat on). From the README it seems like this extension only changes the UA; is that correct? If so it _may_ be doing more harm than good because by changing the UA but not the APIs exposed in the browser (which would let trackers determine the "real" browser version anyway), this extension may actually be making users more uniquely fingerprintable, not less.

**Comment by alerque** [comment]
"This extension" in the context of this issue is which on again?

**Comment by strugee** [comment]
> "This extension" in the context of this issue is which on again?

s/on/one/? This repository is the one that was suggested as a replacement for the old Random Agent Spoofer in the description of nylira/prism-break#1862.

**Comment by neroux** [comment]
Thanks for the comment, with the number of APIs and their differences in different versions and particularly engines it is close to impossible to cover all bases and a determined tracking script will make out the differences, but being foolproof is - to the best of my knowledge - not the goal of the extension.

In case you have an idea on how to improve in certain areas, I'd like to invite you to open a PR. For the time being I'll close this issue.

**Comment by alerque** [comment]
@strugee Oops, I must have ended up here thinking I was still in issues on the PRISM-Break repo. My bad.

**Comment by alerque** [comment]
@neroux I understand what you're saying about the purpose of this addon, but I do think a disclaimer in the README would go a long ways. This is specifically being billed as a way to eliminate "fingerprinting" and uses privacy buzzwords as if it was a complete solution. A disclaimer saying how limited this approach is and explaining that other methods of fingerprinting do exist and that using this might even make those other methods more effective would probably be in the best interest of end users.

**Comment by neroux** [comment]
@alerque These are fair points but it is not necessarily my call to make. I am sure though @tarampampam would consider a PR with a reasonably crafted disclaimer.

**Comment by strugee** [comment]
@alerque hah, no worries!

@neroux I'll file a PR.

**Comment by nxmndr** [comment]
If I understand this right, this consideration is valid under the assumption that a generated UA would be re-used on several websites, that could use said UA to correlate data

Wouldn't the solution then be to pick a new UA for each website you visit ?

**Comment by strugee** [comment]
No, because the fact that your UA is changing at all/randomly provides an additional bit for fingerprinters. This can't be used on its own to uniquely correlate you, but because it's extremely rare, when combined with other device characteristics it's actually quite helpful to fingerprinters.
