### ISSUE TITLE
Per domain disabling option does not work

### ISSUE THREAD

**Issue by gryzor2** [tarampampam/random-user-agent#49]
## Steps to reproduce:
 1. Switch the "Enabled on this domain" to off for a given site
 2. Browse the site and see the User-Agent in server log : it changes

## Expected behaviour:
The User Agent should be constant/probably should be the real one.

## Actual behaviour:
I have noticed this because using ttrss, which ends my session with an explicit error message when the useragent changes.

---------

### System information:
**Browser version**:
```
Firefox 57.0.4 packaged by fedora 26 - x86-64.
```

**Extension version**:
```bash
2.2.0
```

**Console screenshot**:
> **Menu > Settings > More tools > Extensions > Developer mode (check) > Random User-Agent > Background Page**
I don't have this menu.

![Console screenshot](https://cloud.githubusercontent.com/assets/7326800/17556647/98b7f4dc-5f2d-11e6-9eeb-ca2f3dd8e541.png)

**Comment by neroux** [comment]
Thanks for the report, I am afraid though I cant reproduce it. Can you please ensure the site in question is listed in the exception list? What URL is it and what is its exception entry?

**Comment by gryzor2** [comment]
Hi,

Thanks for this prompt reply.
I'd rather not share the exact URL on this public website, however, I do confirm I can see it in the Exception list, in this form 

http?://my.domain.com/*

which I believe matches perfectly the domain I am visiting (which is : https://my.domain.com/tinytinyrss )

**Comment by gryzor2** [comment]
My tinytinyrss problem could be more funky than just a mere User-Agent header change, this is what tinytinyrss seems to use to track useragent 
https://git.tt-rss.org/fox/tt-rss/src/master/lib/Mobile_Detect.php
Looks like they may try to parse different possible headers...

**Comment by neroux** [comment]
That exception syntax should be about right. Would you have another (public) URL where you can reproduce it? For example, whitelisting https://www.whoishostingthis.com/tools/user-agent/ shows the expected result (the real, untampered user agent).

**Comment by gryzor2** [comment]
I confirm I can see a changing behavior on https://www.whoishostingthis.com/tools/user-agent/ whether I whitelist / unwhitelist it.
However, when whitelisted Firefox sends a header that does not match its real version 
It sends : "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

Which is interesting (and I have observed before ever using random-user-agent), since I am running 57.0.4 on linux. I do not know whether this is linked to my tinytinyrss reporting "user agent changed" problem.

**Comment by neroux** [comment]
Could it be the `general.useragent.override` still holds a reference to 51?

**Comment by gryzor2** [comment]
You got it !
After reinitializing all about:config parameters containing the string "useragent" in their name, this all works like a charm, and my problem with tinytinyrss disapeared.
This must have been a residue of some older module. I don't think I fully understand what triggered the UA change into my application, but it now "just works"!

Thank you very much for your support on this "non random-user-agent" matter!

I could make a suggestion : if funky settings about useragent in the config exist, the settings window might hint the user to visit https://support.mozilla.org/en-US/kb/how-reset-default-user-agent-firefox

**Comment by neroux** [comment]
No problem, my pleasure. I like your suggestion, it might be only a bit tricky as extensions now generally do not have access to that information any longer. Maybe some workaround will be possible at some point.
