### ISSUE TITLE
Canvas - AudioContext - Battery API

### ISSUE THREAD

**Issue by gameb0y** [tarampampam/random-user-agent#5]
please block this

Block Audio Fingerprinting:  (Default: disabled; prevent fingerprinting via the AudioContext API)

Block WebGL Fingerprinting:  (Default: disabled; prevent fingerprinting via the WebGL API)

Block Battery Fingerprinting:    (Default: disabled; prevent fingerprinting via the Battery API)

Block Device Enumeration:    (Default: disabled; prevent having hardware devices detected via the WebRTC API)

Block Gamepad Enumeration:   (Default: disabled; prevent having devices detected via the Gamepad API)

Block Canvas Font Access

Canvas Fingerprint
www.browserleaks.com/canvas

AudioContext Fingerprint
https://audiofingerprint.openwpm.com/

Battery API
http://techcrunch.com/2015/08/04/battery-attributes-can-be-used-to-track-web-users/

webrtc unique devices id's and ip leaks
www.browserleaks.com/webrtc

**Comment by tarampampam** [comment]
This extension makes for a working with User Agent only. So, I will not add this features, sorry for this.
