### ISSUE TITLE
Allow custom user agents strings

### ISSUE THREAD

**Issue by repox18** [tarampampam/random-user-agent#50]
Hello, can you add a feature that allows input of unlimited custom user agent strings like it's done in this addon: gitlab.com / alexander255 / user-agent-switcher . I personally like yours because it's much lighter but without having above mentioned feature it's limited to only a few UAs. Thanks for reading.

**Comment by neroux** [comment]
Considering you referred to a Firefox extension I assume you are using Firefox. In this case you already have that feature at hand in the options dialog. Also, because the user agent is randomly created it will provide a much broader subset than just a "few useragents".

**Comment by neroux** [comment]
Did this answer your question @repox18?
