### ISSUE TITLE
The first line of the header is the EXACT and CORRECT user agent data, then the false header is listed.

### ISSUE THREAD

**Issue by gsninsky** [tarampampam/random-user-agent#52]
## Steps to reproduce:
 1.
 2.
 3.

## Expected behaviour:
Tell us what should happen

## Actual behaviour:
Tell us what happens instead

---------

### System information:
**Browser version**:
```
For example: Google Chrome "52.0.2743.116 m", stable channel
```

**Extension version**:
```bash
For example: 2.0.1
```

**Console screenshot**:
> **Menu > Settings > More tools > Extensions > Developer mode (check) > Random User-Agent > Background Page**

![Console screenshot](https://cloud.githubusercontent.com/assets/7326800/17556647/98b7f4dc-5f2d-11e6-9eeb-ca2f3dd8e541.png)

**Comment by neroux** [comment]
Nothing filled out, closing.
