### ISSUE TITLE
JavaScript has the potential to leak authentic User-Agent and operating system information.

### ISSUE THREAD

**Issue by 377573684** [tarampampam/random-user-agent#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When employing the Random User-Agent plugin on the Firefox browser and visiting the website https://www.browserscan.net/?source=adspower_web, it has the capability to identify accurate operating system details and browser User-Agent.

The issue lies in JavaScript unintentionally revealing genuine information. I'm hopeful that an expert can address and rectify this concern. Your assistance in resolving this matter would be highly appreciated. Thank you.

### Steps to reproduce

![企业微信截图_1703609143695](https://github.com/tarampampam/random-user-agent/assets/49289992/1021491d-f44d-4e41-ba0c-f5ec3e86b582)

### Browser

Firefox

### Extension version

V3.18.0

**Comment by RickzDO** [comment]
tested on chromium 87 with XP Pro
the information you posted reveals same as spoofed, so that's the problem ?
same behaviour as mine:
![image](https://github.com/tarampampam/random-user-agent/assets/93270734/b007f2bb-62ae-4910-8daa-5308eeab99a4)
can you give more details which exactly is the bug ?

**Comment by RickzDO** [comment]
the best site to check the bug is here: https://chromiumchecker.com/
tested and for sure there's a huge bug.. this most be fixed !

**Comment by tarampampam** [comment]
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently. Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿

**Comment by RickzDO** [comment]
still the bug is present.. tested with 4.1 ..

see screenshot

![image](https://github.com/tarampampam/random-user-agent/assets/93270734/785b9aa7-7baf-4044-9f67-8377448e4c60)
