### ISSUE TITLE
Addon don't remember the settings.

### ISSUE THREAD

**Issue by Psychosynthesis** [tarampampam/random-user-agent#53]
In the add-on settings, I choose "do not sync between browsers."
Next, I note the User-Agents that I want to use.

Sometimes settings saves correct, but after several browser restarts, the settings are skewed to the original settings.

Config:
1. FF 58.0.2 x64 at Win7 SP1 x64.
2. Addons: AdBlock Plus, Browsec VPN - Free and Unlimited VPN, Google Translator, PureURL, YouTube No Buffer (Stop Auto-playing).
All addons is updated.
3. Last version of Avast.

Console log:
[Random User-Agent] Use fake User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3239.551 Safari/537.36 

P.S. if you can't repeat this - it does not mean that there is no problem. I can't save settings on two different machines - at work and at home.

**Comment by neroux** [comment]
There is a known issue that regarding the browser sync setting (#12). If you leave that setting at its default value the other settings should be saved just fine.

Could you please leave the sync on and try to reproduce it? I'd expect it to work in that case.

**Comment by neroux** [comment]
Could you still reproduce it?

**Comment by Psychosynthesis** [comment]
Thnx. Look like it work.

**Comment by neroux** [comment]
Thanks for the feedback. It would be nice if you could update the rating in that case. Thanks.

**Comment by Psychosynthesis** [comment]
Ok. I change the review.

**Comment by neroux** [comment]
@Psychosynthesis There is an preliminary experimental version at https://github.com/tarampampam/random-user-agent/releases/download/sync/random_user_agent-2.2.3t1-an.fx.xpi which should fix that issue. Would appreciate if you could give it a quick test and let me know if everything works as expected and if the issue is fixed.
Thanks.
