### ISSUE TITLE
Can I switch minutes to seconds?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [tarampampam/random-user-agent#54]
Can I switch minutes to seconds?
In addition, can you add an X-Forwarded-For page that does not refresh the page automatically?

**Comment by neroux** [comment]
The refresh time is fixed to minutes.

As for `X-Forwarded-For`, I am not quite sure what you mean. That field contains the address of the client, in case there is a proxy.

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
@neroux  First of all, I don't want to fix every minute. What I want is to switch random User-Agents every second or every refresh. For example, this extension https://chrome.google.com/webstore/detail/header custom tool/ Maaccnhcoaehdeehahenkmchinbdjjmi Trouble you to install it and use it to understand what I mean. After installation, please open https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes and press F5 several times. Refresh the page, you will see that each time User-Agent is not the same, of course, (X-Forwarded-For) random IP is also very important, because many sites will show where the source of the IP, most of the X-Forwarded-For Get it! ! !

**Comment by neroux** [comment]
Thanks for the suggestions, the IP address is a bit ouf the extension's scope though (also that header would not be reliable).

Going to close this for the time being.
