### ISSUE TITLE
Privacy APIs, required APIs

### ISSUE THREAD

**Issue by kekkc** [tarampampam/random-user-agent#55]
Any plans to implement those:
- Privacy APIs (toggles): https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy 
- Random X-Forwarded-For: e.g. like https://addons.mozilla.org/de/firefox/addon/x-forwarded-for-injector/
- General WebApi toggles: e.g. like https://addons.mozilla.org/de/firefox/addon/webapi-manager/?src=search
- Send referers only when staying on the same domain: e.g. like https://addons.mozilla.org/de/firefox/addon/smart-referer/?src=userprofile or the setting "network.http.referer.XOriginPolicy"=1

In progress, maybe coming if commented that extensions like this need those:
- Provide API to get and set override navigator properties: https://bugzilla.mozilla.org/show_bug.cgi?id=1414078

Alot of extensions currently, but noone that covers even the minimal webextension stuff, or offers any replacement to the original RAS.

**Comment by neroux** [comment]
Thanks for the suggestions, though I guess when there is already a perfectly working extension for a certain privacy area there is little point to re-implement it. Also, the focus of RUA is the user agent, not so much other privacy related areas.

Please find below some more in-depth responses.

> Privacy APIs (toggles)

Many of those settings already seem to be available in the UI of Firefox. Could you elaborate what settings you'd have in mind? Considering RUA is cross-browser these settings should be also available for Chrome.

> Random X-Forwarded-For

Unlikely to be implemented. That header is of indicative nature for proxies and has no fundamental privacy effect.

> General WebApi toggles

The extension you mentioned seems to cover that already pretty well.

> Send referers only when staying on the same domain

Same as above.

> Provide API to get and set override navigator properties

Could you elaborate what you meant? RUA does not override all navigator properties yet, but there shouldnt be any additional work in browser required to do so.

**Comment by kekkc** [comment]
Thanks for the detailed answer, but I guess just focusing on UA is a completely different concept (one that I myself don't understand with 300+ similar addons for FF).

Nevertheless:
>I guess when there is already a perfectly working extension for a certain privacy area there is little point to re-implement it.

Alot of extensions currently, but noone that covers even the minimal webextension stuff, or offers any replacement to the original RAS.

>Many of those settings already seem to be available in the UI of Firefox. 

Hm, changing about:config, FF settings 20 times a day each for problematic websites.

>That header is of indicative nature for proxies and has no fundamental privacy effect.

No fundamental privacy effect?

>RUA does not override all navigator properties yet, but there shouldnt be any additional work in browser required to do so.

You see no advantage in using an webextension than injecting some illegal JS?

No pun intended, I wish you good luck. But please don't hijack other legacy privacy extensions like RAS where people are discussing the background and solutions for UA, JS, Anti-fingerprinting & privacy settings that are alot deeper than a obvious, simple UA change. This only helps if all other settings match, otherwise this is counterproductive and dangerous if people don't know what they're doing.

**Comment by neroux** [comment]
> Hm, changing about:config, FF settings 20 times a day each for problematic websites.

I wrote in the UI.

> No fundamental privacy effect?

Precisely, that header doesnt fool anybody.

> You see no advantage in using an webextension API than injecting some illegal JS?

Illegal? There is nothing illegal about it.

If you can convince all the major browser vendors to support such an API, I am sure that would be the preferred way. Until then overriding it (in a very "legal" way ;) ) is the only option.

> don't hijack other legacy privacy extensions

Excuse me? I did not hijack anything, I merely suggested an extension that I am using and that provides similar functionality with an almost identical name.
