### ISSUE TITLE
Support hotkeys with multiple synced clients on different platforms

### ISSUE THREAD

**Issue by S7uXN37** [tarampampam/random-user-agent#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

As described in the FAQ, hotkeys don't work if the wrong platform is selected as websites use the UA to determine what hotkeys to listen for.
However, I have Chrome synced between two devices with different platforms which means that I either have to toggle the generator settings often or disable the extension on sites where I want hotkeys to work from both devices.

### Suggest a solution

I propose an option to "select platform to match system" in the Generator settings.
On a Windows device this will only select Windows user agents, on Mac only MacOS, etc.

**Comment by tarampampam** [comment]
Is this what you could see? 😄 

![image](https://github.com/tarampampam/random-user-agent/assets/7326800/4c506abd-9ee5-4db3-b1ad-71a5decc3ca9)

**Comment by S7uXN37** [comment]
Yes, that looks good!

I would assume that this option:
a) has no effect on the browser choice, and
b) greys out the OS choices if activated to avoid confusion (maybe different greyed-out shading for the detected "current OS")

Visually, I'd expect the toggle to be below the OS options but that's just nitpicking :D
Also, maybe the description could be "only generate user agents reflecting the actual OS" to be more clear.

Great Job!

**Comment by tarampampam** [comment]
I'm closing this issue because the described problem seems to be fixed in the new version, which was released recently (here is the [link](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0)). Feel free to reopen it or ping me if it still brings any problems. Thank you for reporting the issue and for your attention to this project! 👍🏿
