### ISSUE TITLE
🎉 Need help with `v4` alpha|beta testing

### ISSUE THREAD

**Issue by tarampampam** [tarampampam/random-user-agent#572]
Hello everyone!

I've been hard at work over the past few weeks on a major overhaul of the extension. Why major, you ask? Well, I'm migrating it to MV3 (manifest version 3), swapping out Vue.js for React, and transitioning from Webpack to Vite. Since this involves rewriting most of the codebase, I've opted to start from scratch.

This means a fresh version untethered from the legacy codebase (which is great!), but it also comes with its fair share of new bugs, naturally! 😄

So, I'm reaching out to see if anyone would like to assist with early testing of the extension. I can provide early builds via messages in this thread, and it would be fantastic if you could run them locally and provide feedback on whether everything is working smoothly or if you encounter any issues.

Please leave a comment to let me know if you're willing to help out. Your assistance would be greatly appreciated!

/cc @S7uXN37 @meichengg @TheGITofTeo997 @yozachar @377573684 @tobyink @tomac4t

**Comment by meichengg** [comment]
Sure thing, i can assist with that.

**Comment by S7uXN37** [comment]
Yes, I can also help with that, Kudos to you for tackling that overhaul!

**Comment by tarampampam** [comment]
Guys, great news - I have completed the main rewriting process, and I am excited to share the first v4 build for testing purposes:

[Download v4.0.0-alpha-1](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0-alpha-1)

> To install the extension into your browser, download the archive with the distributive for your browser, unpack it somewhere, open the addons/extensions page, and press the "Load unpacked extension" button

Feel free to test it and share your feedback. Please report one bug per comment if possible, as this will help me address them more efficiently. No need to create separate issues for each bug - it could be overwhelming.

Here are the main changes:

- Improved JavaScript protection (you can test it [here](https://webbrowsertools.com/useragent/); the real user-agent leaks only on aggressive UA header detection).
- CloudFlare infinite loop issue appears to be fixed (although not completely certain; you can test it [here](https://cf-challenge-test.random-user-agent.com/)).
- The popup window now allows selection of OS and browser, plus an option to sync the OS with the host OS.
- Domain wildcard rules are no longer available.

Known issues:
- chatgpt.com won't work when the extension is enabled

**Comment by tarampampam** [comment]
Guys, do you have any news?

**Comment by S7uXN37** [comment]
Hey everyone,

* I can confirm that agressive UA header detection differs from the other methods and does not reflect the parameters picked in the extension (as expected)
* CloudFlare works on (Chrome, Windows) - ChatGPT does not (as expected)
* OS Sync correctly determines the host OS on (Chrome, Windows) and (Chrome, MacOS)

Bug: Cloud Flare test page loops when accessing from MacOS.
Let me know if there's any debug info you can use.

Other than that: no bugs to report so far :) I'll keep testing and add more comments if I encounter any.

**Comment by tarampampam** [comment]
I have one more piece of news - it seems like an infinite CloudFlare loop has been completely fixed by adding `challenges.cloudflare.com` to the `alwaysExcludedFor` list:

![image](https://github.com/tarampampam/random-user-agent/assets/7326800/1e803c62-0e2b-4e5d-954f-4855e4bbddc0)

After this fix, even ChatGPT works as expected (though it may require an additional page refresh). Nonetheless, a fresh build is already available for downloading:

https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0-alpha-3

**Comment by yozachar** [comment]
> Guys, do you have any news?

I tested  it on LibreFox, but for some reason the UA OS remained Windows. I suspect it has do something with the browser config.

**Comment by meichengg** [comment]
I confirm `v4.0.0-alpha-5` works well for chatgpt.com and such other websites that has CloudFlare captcha and the current exclusion for `challenges.cloudflare.com` really works. Good work! 🔥

**Comment by S7uXN37** [comment]
Possible bug in alpha-1 (or alpha-3; not quite sure)?

Upon upgrading to alpha-5, I found the following error messages in the Extension Manager (Chrome):
![image](https://github.com/tarampampam/random-user-agent/assets/8556523/96debda1-abbd-4a54-ac7b-8e8b40b43b5d)

The details are the same for the second error type.

**Comment by tarampampam** [comment]
@S7uXN37 Did you press the "reload extension" button after updating the sources? Usually, errors like that occur when you forgot to do that :D

**Comment by S7uXN37** [comment]
@tarampampam These errors were present before extracting the new alpha-5 version of the extension 🤔

In other news, ChatGPT works for me again - as does the test page on MacOS 🎉

**Comment by meichengg** [comment]
> In other words, should I release the alpha-5 version to everyone, or is it still too early? What do you think, guys?

Let public test it, so far i don't see any error on Firefox, i haven't tested with Chrome yet, if they found bug, they would open an issue 😸

**Comment by S7uXN37** [comment]
I agree, I don't observe any significant bugs

**Comment by tarampampam** [comment]
Sounds like a plan!

> - It's a ~~key~~ plan!
> - No! Much more better. It is a *drawing* of a ~~key~~ plan!
> ![image](https://github.com/tarampampam/random-user-agent/assets/7326800/96228a9d-f148-4f62-a57a-d520080e4416)

**Comment by tarampampam** [comment]
Thank you to everyone who helped me test the new version. Guys, you're awesome!

A new version was just [released](https://github.com/tarampampam/random-user-agent/releases/tag/v4.0.0) a few minutes ago. It's already available for Firefox, and in 24 hours, it should become available for Chrome users. If any new bugs are found, please create separate issues - one per bug, as usual. And I'm going to open a bottle of beer while awaiting issues with titles like "You broke everything! The previous version was better! Fire in the hell!" :D
