### ISSUE TITLE
Problems with modifying the User Agent in Firefox after the update

### ISSUE THREAD

**Issue by 0CTYSA** [tarampampam/random-user-agent#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Description:**

The extension was working correctly before the update. However, after updating to version [4.0.1] following recommendations, I noticed that it does not modify the User Agent in Firefox, even after setting various parameters for the change.

Test with iOS:
![image](https://github.com/tarampampam/random-user-agent/assets/119985966/c7bc58fa-c73a-4295-8af8-97ef43b6c17b)

### Steps to reproduce

**Steps to reproduce the problem:**
1. **Test with iOS:**
   - I activate the extension in the iOS options.
   - I use the tool at [webbrowsertools.com](https://webbrowsertools.com) to verify the change of User Agent.
   - I set the version of iOS as a parameter.
   - I observe that the User Agent does not change.

**Expected Results:**
The User Agent should change according to the parameters set in the extension settings.

**Actual Results:**
The User Agent does not change after adjusting the parameters.

**Additional Information:**
- **Browser:** Firefox
- **Extension Version:** [4.0.1]

**Images:**
- Extension configuration:
![iOS Configuration](https://github.com/tarampampam/random-user-agent/assets/119985966/136566cd-4697-49bb-9ed6-314369ddb6f2)
  
- Result on webbrowsertools.com:
![Test Result](https://github.com/tarampampam/random-user-agent/assets/119985966/d5860784-0a95-41e3-81a3-f5adca7f3ac2)

---

### Browser

Firefox

### Extension version

4.0.1

### Anything else?

**Remarks**

- The extension still does not work, even after restarting the browser.
- I have tried uninstalling and then reinstalling the extension, but the issue persists.
- The icon, which is supposed to turn red when the extension is active, remains gray.
- This problem affects all websites, indicating a possible issue with the extension's activation mechanism.

**Comment by tarampampam** [comment]
Confirmed, thank you for your issue! I'll try to fix it ASAP

**Comment by tarampampam** [comment]
I found and successfully fixed the bug. It seems like it only affected Firefox. The fixed version will be released shortly!

**Comment by tarampampam** [comment]
A fixed version has been published. Please try to force the addons to update, and feel free to write here if something still goes wrong. Alternatively, you can open a new issue if you find any more bugs 😉

**Comment by 0CTYSA** [comment]
@tarampampam 
You are very kind, I have indeed checked, and the correction was successful. 
Thank you very much for the prompt solution! 🫶
