### ISSUE TITLE
Make Google Analytics events system optional and/or provide a privacy friendly alternaive

### ISSUE THREAD

**Issue by ekaflaereht** [tarampampam/random-user-agent#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem to be solved

Since version 4 you have added Google Analytics to track the users using your extension. ("The extension now collects statistics using the Google Analytics events system (reporting errors and the total amount of browsers run with the extension)"

I was kind of shocked when I read this, especially when I realized there was no option to opt out.

Ignoring the fact that this is most likely illegal in EU without confirmation by the user because of GDPR, you are adding to mostly a privacy related extension one of the biggest data collectors and tracking company's world wide.

It might be even the case that they are able to provide each user of you extension a unique ID making them traceable through the whole Google universe even if they remove cookies, do not login in Google and so on.

I mean you kind of describe this situation even in the change log or how should you track the total amount of browsers if you do not prevent multiple counting of the same user?

### Suggest a solution

At least make the analytics part optional.

Even better would be to not use Google but a more privacy friendly company, e. g. one of these: https://opensource.com/article/18/1/top-5-open-source-analytics-tools

### Additional context

I haven't tested this and I do not know the exact succession but are ad blockers like Ublock able to block your extension's Google Analytics connection or is this run independently/before and thus undermining the user approaches to improve their privacy online? 

Your extension is great and I can not thank you enough for your great work but this change log entry was shocking to me.

**Comment by tarampampam** [comment]
Already done in #585

**Comment by ekaflaereht** [comment]
Yes, many thanks. :bow: I have checked the opened and closed issues, the latest release notes but did not look at the prs.

**Comment by tarampampam** [comment]
And since we are discussing alternatives, can you suggest any options to handle errors and stats in a more privacy-conscious manner?

**Comment by ekaflaereht** [comment]
I am no expert there, but what about [Matomo](https://github.com/matomo-org/matomo) or [Piwik](https://piwik.pro/)?

For the first you need your own web server to not include any additional costs, the second has a limit per day in the free version.

But analytics is not mandatory and Google Analytics is only free because they immensely increase their user data extraction on a significant part of the Internet without them having to pay a dime besides their hosting/development costs.
