### ISSUE TITLE
Activate statistics collection parameter cannot be turned off

### ISSUE THREAD

**Issue by gelavat** [tarampampam/random-user-agent#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello.
When I uncheck the "Activate statistics collection" switch, it is properly disabled but when I change the options tab and come back to the main parameters, it is unchecked again.

This is a bug, because all other parameters are properly kept, only this one is not being saved.

Can you please save this parameter too, each time it is switched ?

Regards.

### Steps to reproduce

1. Go to General parameters tab in the extension's options.
2. Turn off the last parameter "activate statistics collection"
3. Go to the Blacklist parameters tab
4. Go back to the General parameters tab
5. The "activate statistics collection" parameter is turned on again and in green. It should have been saved as turned off and displayed as turned off.

### Browser

Firefox

### Extension version

4.1.0

**Comment by tarampampam** [comment]
Outch, the bug is confirmed. I'll make a fix ASAP

**Comment by gelavat** [comment]
Thank you very much. And thanks for your great plugin!

**Comment by tarampampam** [comment]
@gelavat I've made a fix, but I'm still not completely sure it resolves the issue. Therefore, I'll keep this issue open even after the PR is merged and the release is published. Could you please confirm here if the issue is resolved after you receive the update? Thank you.

**Comment by tarampampam** [comment]
I have published a fresh release [v4.1.1](https://github.com/tarampampam/random-user-agent/releases/tag/v4.1.1)

**Comment by gelavat** [comment]
Great, this fix works for me.
Thank you very much, all is fine now.
