### ISSUE TITLE
Question on website matching

### ISSUE THREAD

**Issue by enervated** [tarampampam/random-user-agent#6]
I have a feeling I'm going to feel stupid when I find the answer, but could someone please explain the reasoning behind the options to "Disable agent switching when a website matches the following rules: Internet Explorer 6 / Chrome on Mac / Firefox on Mac / etc."?

I understand that the UA contains browser and OS info, but what does it mean for a website to match that?

**Comment by SmudgedMuffin** [comment]
Could you provide a screenshot of what you're seeing on your end?
I don't see an option matching that in v2.1.0 and there shouldn't be the whole bit about the browsers.
A screenshot would be very helpful in figuring out this issue.

Thanks!

**Comment by enervated** [comment]
Sure, thanks, I'm asking what these settings mean:

![image](https://cloud.githubusercontent.com/assets/11533799/18652969/95bdb24e-7ea4-11e6-8de3-f06fafe3ae7f.png)

**Comment by SmudgedMuffin** [comment]
That should not be there. I see now (on my end) what you're talking about.
I will let the developer know about this so he can fix this (it's supposed to say something about selecting which browsers you want to add to the randomization list).

Thanks for pointing that out!

**Comment by tarampampam** [comment]
Thx 4 your reporting!
