### ISSUE TITLE
Feature Request: User agent update on google chrome extension

### ISSUE THREAD

**Issue by quangthienit158** [tarampampam/random-user-agent#61]
Why do not you update to the latest UAGenerator.js for the chrome extension?

**Comment by neroux** [comment]
What do you mean?

**Comment by quangthienit158** [comment]
I want to update the new UA for chrome

**Comment by neroux** [comment]
I misunderstood your question. Please see me edited response.

**Comment by quangthienit158** [comment]
how can I contact him?.

**Comment by neroux** [comment]
By tagging him on Github.

I did send him a follow-up email though and hope he gets back to you soon.

**Comment by quangthienit158** [comment]
Yep.Thank you.

**Comment by quangthienit158** [comment]
Hi @tarampampam 

Can you help me update UA in random user agent on chrome ?
The current version of UA on Chrome is very old compared to the current version.

**Comment by tarampampam** [comment]
@quangthienit158 - Version `2.2.5` just released in [google webstore](https://chrome.google.com/webstore/detail/einpaelgookohagofgnnkcfjbkkgepnp/). Usually publication takes about 20 minutes.

@neroux - dude, you are best, thx for your contribution ;)
