### ISSUE TITLE
Random agent upon opening new tab

### ISSUE THREAD

**Issue by cwross** [tarampampam/random-user-agent#62]
First - thanks for this plugin!

I use the plugin to help add "noise" to fingerprinting/tracking efforts as I browse the web. It would be useful if, in addition to the option to have the agent change after X number of minutes, you could add an option to automatically pick a random user-agent for each new tab that is opened.

Thanks!

Charlie

**Comment by neroux** [comment]
Hello Charlie,

thanks for the suggestion but could you please elaborate a bit on how that would be different from setting the refresh to one minute? In that way the user agent would be also fairly often changed. I am not sure tying it to opening a new tab would fundamentally change much.
