### ISSUE TITLE
User Agent in Web worker and Top window&Frame are different

### ISSUE THREAD

**Issue by h1toru** [tarampampam/random-user-agent#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I did scans on https://vytal.io/scan

Here's the result:

**Random User-Agent** (with *Protect against detection by JavaScript* enabled)

![image](https://github.com/user-attachments/assets/be5d58e2-ede0-4242-891a-eb59b0a3449d)

**Vytal**
> Vytal is a browser extension to spoof timezone, geolocation, locale and user agent.

![image](https://github.com/user-attachments/assets/225cebe9-f42e-44cd-8e15-8e68659984a8)

### Steps to reproduce

1. Go to https://vytal.io/scan
2. Enable Random User-Agent Switcher
3. Save the result
4. Disable Random User-Agent Switcher
5. Apply Vytal User Agent Spoofing
6. Reload
7. Save the result

### Browser

Chrome

### Extension version

4.3.0

### Anything else?

Vytal source code: https://github.com/vytal-io/vytal-extension

**Comment by tarampampam** [comment]
Unfortunately, this is a known issue, but thank you for highlighting it!
