### ISSUE TITLE
[aggressive] UA Header shows true user agent.

### ISSUE THREAD

**Issue by vladnero1** [tarampampam/random-user-agent#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://webbrowsertools.com/useragent
"[aggressive] UA Header" on this website shows true user-agent.

### Browser

Chrome

### Extension version

4.3.0

### Anything else?

https://webbrowsertools.com/useragent
![Screenshot_26](https://github.com/user-attachments/assets/ad0bdf61-8f4e-422c-b6ef-0644655851c4)

**Comment by tarampampam** [comment]
This is a known issue, unfortunately

https://github.com/tarampampam/random-user-agent/blob/36f6926c48d0f1f639b9081ee9347e469a876d81/README.md?plain=1#L58
