### ISSUE TITLE
Sync extension settings between browsers does not work

### ISSUE THREAD

**Issue by hoangthong1989** [tarampampam/random-user-agent#63]
I'm using Random User-Agent 2.2.5 for firefox 52
and I can not activate Sync extension settings between browsers
When I open firefox Sync extension settings between browsers are in off mode

**Comment by neroux** [comment]
Are you sure it is Firefox 52? If so, its an error in the compatibility declaration as only Firefox 57+ is supported I am afraid.

**Comment by hoangthong1989** [comment]
Yes, I am using firefox 52
and I have tried to download the version of Radom-user-agent is lower than
but does not work

**Comment by neroux** [comment]
A lower version wont work, as they all require Firefox 57+. Only from that version webextensions are fully supported (there is some preliminary support in earlier versions like 52 but no full support).

Please upgrade to Firefox 61 (if you dont want to fully give up 52 yet, you can also use the portable version and run a second browser profile in parallel) and check if you still experience the issue. That should fix it.
