### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by cig0** [tarampampam/random-user-agent#64]
Hi,

Is there any (remote!?) chance we can have this awesome add-on for Safari?

Thanks a lot

**Comment by neroux** [comment]
Hello Martin,

Safari (currently) does not support webextensions, which would mean it would require a complete rewrite of RUA. So (for the time being at least) I am afraid it will be probably relatively unlikely for RUA to show up on Safari as well.

**Comment by cig0** [comment]
:'(

Thanks!
