### ISSUE TITLE
User-agent is not complitely changed

### ISSUE THREAD

**Issue by HuMuK** [tarampampam/random-user-agent#65]
I am using the Firefox under windows. 
This info gives https://amiunique.org/fp as user-agent:
"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_2; en-PH) AppleWebKit/536.10.17 (KHTML, like Gecko) Version/11.1.5 Safari/536.10.17"

**Comment by neroux** [comment]
And what is incorrect about that?

**Comment by neroux** [comment]
As you just edited an additional question into your original posting, here the answer

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
