### ISSUE TITLE
Fake Screen Size

### ISSUE THREAD

**Issue by quangthienit158** [tarampampam/random-user-agent#66]
![sen](https://user-images.githubusercontent.com/35558281/43989030-5dc34854-9d10-11e8-9625-1fc8b74a21b9.JPG)
I think changing the screen size for the browser is really necessary.
I think this will make anonymity become better.
I expect a change from you.

**Comment by neroux** [comment]
That is beyond the current scope of the extension. RUA only tackles the user-agent so far.

>  I expect a change from you.

I presume you are not a native speaker, so no offence taken but that wording really came off a bit wrong :)
