### ISSUE TITLE
random-user-agent It doesn't work on this web page

### ISSUE THREAD

**Issue by gqzc** [tarampampam/random-user-agent#67]
random-user-agent It doesn't work on this web page
http://www.runoob.com/try/try.php?filename=try_nav_all
In this web page, it is still my own UA.
![qq 20180813184252](https://user-images.githubusercontent.com/42342148/44027412-fbf18ae4-9f28-11e8-9dae-fbfe3facb30d.png)

**Comment by neroux** [comment]
That seems to be related to #36. Unfortunately there is not much that could be done at this moment, as this is a limitation of Chrome, which has been known for the past eight years.
