### ISSUE TITLE
RUA Breaks Facebook

### ISSUE THREAD

**Issue by anonkat** [tarampampam/random-user-agent#68]
Do you know if Facebook is doing something to block your add-on? For the longest, longest time, my message boxes have been disappearing. One by one, I disabled all add-ons and enabled them again - finally ONLY disabling random user agent on Facebook, and the message boxes come back. 

Is this a bug? Is this something Facebook did that you can fix?

Thanks much!

anoncat

**Comment by neroux** [comment]
That is probably regular browser sniffing. Try to select only browsers which match your actual browser and check if you still experience the issue. If not, Facebook is delivers different content depending on the browser, which breaks in this case you as you claim to be a different browser than you actually are.

**Comment by anonkat** [comment]
You know what? That makes a LOT of sense! Thank you!
