### ISSUE TITLE
Doesn't randomising make you more unique?

### ISSUE THREAD

**Issue by aschrijver** [tarampampam/random-user-agent#77]
In a number of Hacker News (news.ycombinator.com) threads I have read that randomizing the User Agent might only serve to make you stand out in the crowd. I can't find the specific discussions now, but it values considering whether or not this is the case.

A better strategy might be to set a fixed, most commonly used User Agent.

**Comment by neroux** [comment]
I'd probably quote the great Mark Twain in this context and claim these reports are (greatly) exaggerated and generalised. However there is still a certain truth in it, that claiming to be one browser but fingerprinting to another might make your more unique. It really depends on what the site, you'd like to protect against, is evaluating.

If that is of concern for you, you can simply pick only user agents matching your actual browser.

**Comment by aschrijver** [comment]
I was just wondering whether this was the case, but I don't know enough on what data is actually collectable (other than what [Panopticlick](https://panopticlick.eff.org/) is telling me.

Also I had just included a similar extension (FF-only) that allowed setting the `User-Agent` to [awesome-humane-tech](https://github.com/engagingspaces/awesome-humane-tech), to which I just added your project too.

You can close if you want, or leave open for others to vent their opinion :)

**Comment by neroux** [comment]
Partially it probably is the case as modern browsers provide a lot of places to hook in an fingerprint them. So if a site uses such an approach and then tries to match the report user agent it could notice that discrepancy, which could make you more trackable. For these cases it would be really best to only select the profiles matching your browser.

However I cant tell you how common that might be. If it is, the entire landscape of tools faking different user agents will erode, unless they find a way to mock a different browser platform in its entirety.
