### ISSUE TITLE
Ломает отображения картинок на сайтах.

### ISSUE THREAD

**Issue by gegemon2012** [tarampampam/random-user-agent#79]
Возникла одна проблема. Включение настройки "Cкрывать настоящий User-Agent при определении средствами javascript (экспериментально)" ломает отображение картинок на некоторых сайтах (например aliexpress), при этом если добавить сайт в исключение проблема не решается пока не отключишь настройку полностью. Отключать ее не особо хочется. Можно ли это исправить?

P.S. Со временем проблема возникает снова даже если отключена соответствующая настройка. Помогает вк/выкл дополнения.

**Comment by neroux** [comment]
Thats a browser sniffing issue and there is nothing you can do except disable the extension for that site.

**Comment by neroux** [comment]
Which browser are you using? Do you have some test URL where it happens?

It most likely has nothing to do with the extension but is simply regular browser sniffing.

**Comment by gegemon2012** [comment]
Проблема проявилась после установки firefox 57 x32. Сейчас использую firefox 63 x32.
Тестовый URL [https://best.aliexpress.com/?cv=0&af=208&cn=43ph53x74brxy5ouae5pf6a3cumbwcmr&dp=v5_43ph53x74brxy5ouae5pf6a3cumbwcmr&af=208&cv=0&cn=43ph53x74brxy5ouae5pf6a3cumbwcmr&dp=v5_43ph53x74brxy5ouae5pf6a3cumbwcmr&afref=&aff_platform=default&cpt=1540446236033&sk=ccfBY4yg&aff_trace_key=ee0214aeca9c42939d84401844c608c8-1540446236033-06967-ccfBY4yg&terminal_id=a69b7d16c02f4eb7be6a5f4b3662985f](url). При этом эта проблема возникает при переходе по любой ссылке aliexpress. Также по ссылке [https://market.yandex.ru/](url) наблюдаются такие же проблемы как на главной странице так и на страницах товаров. 

The problem manifested itself after installing firefox 57 x32. Now I use firefox 63 x32. Test URL [https://best.aliexpress.com/?cv=0&af=208&cn=43ph53x74brxy5ouae5pf6a3cumbwcmr&dp=v5_43ph53x74brxy5ouae5pf6a3cumbwcmr&af=208&cv=0&cn=43ph53x74brxy5ouae5pf6a3cumbwcmr&dp=v5_43ph53x74brxy5ouae5pf6a3cumbwcmr&afref=&aff_platform=default&cpt=1540446236033&sk=ccfBY4yg&aff_trace_key=ee0214aeca9c42939d84401844c608c8-1540446236033-06967-ccfBY4yg&terminal_id=a69b7d16c02f4eb7be6a5f4b3662985f] (url). However, this problem occurs when you click on any aliexpress link. Also on the link [https://market.yandex.ru/] (the url) there are the same problems both on the main page and on the product pages.

**Comment by neroux** [comment]
On Firefox the JavaScript setting does not have any effect at all, as Firefox will automatically replace the user agent value with what was supplied in the host header. See #60

Again, this is most likely a browser sniffing issue of that site. You can verify it by selecting only Firefox from the list of user agents and checking if the issue disappears in this case.
