### ISSUE TITLE
Changing request headers for better anonymity (function request)

### ISSUE THREAD

**Issue by Lichtenshtein** [tarampampam/random-user-agent#8]
Some sites make checks for headers such as Accept, Accept-Encoding, Accept-Language, etc and if they don't match the browser's UA it results in captcha requests and other unpleasant things. Would be useful to mask them to the current browser's UA (IE, Firefox, Safari).

**Comment by tarampampam** [comment]
This headers (*like Accept, Accept-Encoding, Accept-Language*) is typical for most used browsers, and do not need to be changed. Can you show me sites, where you got errors?
