### ISSUE TITLE
YouTube interface display issue.

### ISSUE THREAD

**Issue by jcAr7nSB** [tarampampam/random-user-agent#80]
Everything is loaded normally only with some defined ua. 
Only displays video, the other elements are not loaded. 
![yt_error](https://user-images.githubusercontent.com/44696262/47905538-cff6ed00-dea0-11e8-9d54-bc853d9d4e09.png)

**Comment by neroux** [comment]
Please follow the guidelines on how to submit a bug and fill out all required information (it was right there where you submitted the issue).

After having received the full bug report we can look into it and reopen the issue.

**Comment by jcAr7nSB** [comment]
Hi, unfortunately, I do not know English well. Perhaps this is why I understood some information not as expected.
I read “Contributing” and “Code of Conduct” on the page “https://github.com/tarampampam/random-user-agent/issues/new”.
Unfortunately, I did not find there specific information on how to send an error message and fill in all the necessary information. In particular, I did not find there specific information, which indicates that I should send “a full error report (in particular, versions (which?)).
I really do not understand what I could miss. Please clarify what you mean.
Please tell us how to create a "complete error report (in particular, version numbers (of what?)."
If you mean the version numbers of the installed extension and the browser version, here they are:
Firefox Quantum 63.0 (64 bit);
Random User-Agent 2.2.7 (updated October 30).
Honestly, I did not find there information that needs to be reported.
I hope I correctly translated what I had in mind.
Thanks.

**Comment by neroux** [comment]
Its the bits from https://github.com/tarampampam/random-user-agent/issues/new?template=bug_report.md. Particularly the system information part.

So, you are using the extension on Firefox, right? Which browsers did you pick in the selection box of the extension? If you experience the issue only with non-Firefox browsers it most likely is a browser sniffing issue and hence a problem of the website.

**Comment by neroux** [comment]
Alright, that explains the missing bits.

Back to the issue though, what user agents have you configured and using which one do you experience the problem?

**Comment by jcAr7nSB** [comment]
Please wait a bit, I'm already writing.

**Comment by neroux** [comment]
This is most likely the same issue as #41.

**Comment by jcAr7nSB** [comment]
Yeah, right, on Firefox.
The following browsers were selected in the extension selection window:
All Windows: Edge, Chrome, Opera, Firefox;
And all Linux: Chrome, Opera, Firefox.

Further on the pattern:

### Expected behavior:

> Everything except "Firefox UA".

### Actual behavior:

> The page does not display all items.

### Steps to reproduce behavior:

1. Go to any YouTube video.
2. The extension is included, including without exception this domain.
3. See Error

### Screenshots

> I was previously added.
>
>! what does & rarr; mean? 
You need a text from here? - "moz-extension://e556d26a-82ee-4a2e-859a-482c6c6a1e21/manifest.json": 
![rua](https://user-images.githubusercontent.com/44696262/47913741-9f21b280-deb6-11e8-994a-22e5684bd989.png)

## System information

### Desktop (please fill in the following information):

- OS: `Windows`
- Browser: previously reported
- Version: previously reported
- The user agent for which the problem occurs:
many, for example:
- Mozilla / 5.0 (Windows NT 6.3, Win64; x64) AppleWebKit / 537.36 (KHTML, for example, Gecko) Chrome / 68.0.3440.3 Safari / 537.36 OPR / 44.0.2100.252

probably yes, this is # 41. It is still not solved?

**Comment by jcAr7nSB** [comment]
Is "document.registerElement" possible to cure with a script in the extension of (any)monkey?

**Comment by neroux** [comment]
> Mozilla / 5.0 (Windows NT 6.3, Win64; x64) AppleWebKit / 537.36 (KHTML, for example, Gecko) Chrome / 68.0.3440.3 Safari / 537.36 OPR / 44.0.2100.252

So yes, a browser sniffing issue.

> It is still not solved?

This is not an issue of the extension and cant be fixed there. It is an issue of the site as it returns invalid JavaScript for Firefox and needs to be addressed by Google.

> script in the extension of (any)monkey?

I dont think so as we are talking about some core functions but if you come up with a fix for Youtube and post it here it will be definitely appreciated.

Please see #41 for workarounds.

**Comment by neroux** [comment]
>  Probably should change in the extension of the current link to this.

Should be fixed with the next version.
