### ISSUE TITLE
Chrome version numbers

### ISSUE THREAD

**Issue by GrimPixel** [tarampampam/random-user-agent#81]
I see this add-on is really generating random combinations, including impossible ones. Every time it is unique in Panopticlick test. So, if I were the one to fingerprint, I can easily find these combinations and tag these people as users of this add-on.

**Comment by neroux** [comment]
Impossible such as?

**Comment by GrimPixel** [comment]
Well, sorry I didn't explain it well.
It appeared to be unique with the default setting (Chrome on Windows, Chrome on Mac, Chrome on Linux are enabled), always being something like 
“Mozilla/5.0 (...) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/... Safari/537.36”
They are unique. So I doubt if the randomly generated “...” value combinations can exist if they are not fake. As the first “...” does not vary much, I guess something went wrong with the second “...”, versions of Chrome.
I have tried many times. I am not a Chrome user, but I doubt if Chrome releases are like “68.0.3440.19”, “68.0.3440.2”, “68.0.3440.21”, which are generated by this add-on.

**Comment by neroux** [comment]
> It appeared to be unique with the default setting (Chrome on Windows, Chrome on Mac, Chrome on Linux are enabled), always being something like
“Mozilla/5.0 (...) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/... Safari/537.36”

Of course, that's Chrome's user agent, if you only pick Chrome that's what you will always get by design.

> They are unique. So I doubt if the randomly generated “...” value combinations can exist if they are not fake. As the first “...” does not vary much, I guess something went wrong with the second “...”, versions of Chrome.
I have tried many times.

I am sorry, I am not sure what you mean by that.

> I am not a Chrome user, but I doubt if Chrome releases are like “68.0.3440.19”, “68.0.3440.2”, “68.0.3440.21”, which are generated by this add-on.

I cant guarantee for the fourth number, but what should be wrong with them?

**Comment by GrimPixel** [comment]
I don't know if it is really released with the fourth number being continuously from 19 to 21, but this seems to be abnormal.

**Comment by neroux** [comment]
So your concern is that last number in the Chrome user agent?!

**Comment by GrimPixel** [comment]
I think when the first three numbers are determined, the fourth number should not be continuously from 0 to 999. It should be very limited.

**Comment by neroux** [comment]
I understand your point, however these numbers frequently change during the development process of each version and it is hard to track which numbers are actually official ones.

It could be certainly incorporated however if you can submit regular pull requests with such updates.

Generally speaking I dont think that number is a huge red flag as far as user tracking is concerned. If someone digs that deep I'd assume #47 is of much more concern.

**Comment by GrimPixel** [comment]
OK, maybe I can choose other browser options to avoid this.

**Comment by neroux** [comment]
Sure, thats what that feature is there for :)

**Comment by neroux** [comment]
@GrimPixel, 3bd9b8d addresses your concern and limits that number from 80 to 144.

**Comment by neroux** [comment]
@GrimPixel, just as information, that change is live as of 2.2.9
