### ISSUE TITLE
Work only with a list and random change time

### ISSUE THREAD

**Issue by Agagamand** [tarampampam/random-user-agent#83]
Request for new functionality:
1. «Random User-Agent» replaces the user agent only on sites from the list.
2. «Random User-Agent» changes the user agent not at the same time, but at random (the user indicates the intervals). Its very need for defend fingerprint a browser.

**Comment by neroux** [comment]
I am not quite sure about your second idea. Do you mean the user agent should not be refresh at a fixed interval but at an interval in a defined time window? How would that improve any fingerprinting?

**Comment by Agagamand** [comment]
> Do you mean the user agent should not be refresh at a fixed interval but at an interval in a defined time window?
Yes.

> How would that improve any fingerprinting?
I don't speak English well, it's hard for me to explain. But this feature would really improve security.

**Comment by neroux** [comment]
That second suggestion should be quicker to implement than the first one but there should be a valid reason for it. Regardless of your level of English, please try to explain why a random value between X and Y is better than a static Z.

**Comment by Agagamand** [comment]
Когда юзер-агент меняется через фиксированный промежуток времени, то теоретически это облегчает определение что за разными юзер-агентами скрывается один и тот же пользователь. Да, при соблюдении всех правил приватности такой расклад будет маловероятным, но если есть другие косвенные свидетельства того, что под разными User-Agent скрывается один и тот же человек (заблокированные cookie, необычное разрешение экрана, один и тот же IP-адрес, и тому подобное), то смена User-Agent спустя фиксированное время (при сохранении других косвенных свидетельств) может стать дополнительным косвенным свидетельством для определения пользователя.

Возможно, я погорячился, сказав что, смена User-Agent в разное время это очень важно. Но, тем не менее, в некоторых случаях, это действительно затруднит определение пользователя.

Тем более что люди не склонны менять настройки. Я уверен, что 90% пользователей «Random User-Agent» оставили настройки по умолчанию, т.е. смену юзер-агента спустя каждые 10 минут. Как это поможет в определении пользователя? Если тот, кого есть желание вычислить, беспокоится о приватности, то можно предположить что он будет использовать «Random User-Agent», а рас так, то для его идентификации в сети стоит ожидать что его User-Agent будет меняться, а если юзер-агент будет меняться спустя фиксированное время, то данный факт легче вычислить, легче установить зависимость и идентифицировать пользователя.

**Comment by neroux** [comment]
I cant tell how accurate the automated translation was but I believe I get your point.

**Comment by tarampampam** [comment]
@Agagamand Sorry for the late reply. Is this option still relevant?
