### ISSUE TITLE
Anti-Paywall Functionality

### ISSUE THREAD

**Issue by Agagamand** [tarampampam/random-user-agent#84]
This function does not directly relate to the topic of the «Random User-Agent», but will make it more universal.

Can you make it possible to assign a specific user agent to a specific site? Suppose that chip.de always gave the user agent Android Chromium, or some other (user will choose or write)?
That is, without changes, that the site chip.de always has the selected user agent

P.S.
Inspired by https://github.com/nextgens/anti-paywall

**Comment by Agagamand** [comment]
> Again about Chrome UA problem in youtube when using Firefox. As making profiles is long-time work and needs lots of efforts, maybe we start from a simple thing. Under "Enabled on this domain" checkbox add "Freeze UA for this domain". How it works: user selects some random UA using "Get new agent" and clicks "Freeze". Now, when timer wants to change UA to a new random one, it checks if the UA is frozen for this domain and if it is frozen, it skips UA change. So, when we work in youtube, we freeze the UA for youtube and the plugin keeps some workable "Firefox" UA until it is unfrozen, 

Yes!

**Comment by neroux** [comment]
Thanks for the clarification. Closing this as duplicate then.
