### ISSUE TITLE
Скорее не ошибка, а пожелание

### ISSUE THREAD

**Issue by somsern** [tarampampam/random-user-agent#89]
Здравствуйте, уважаемый. Извините, что пишу на русском языке - не знаю английский. Суть проблемы: У меня есть необходимость чистить браузер программой CCleaner. И с недавнего времени после очистки cookie-файлов стали слетать настройки Random user-agent. После очистки настройки откатываются к базовым (10 минут, три базовых браузера...). Есть подозрение, что это после последнего обновления. Если данную ситуацию нельзя исправить, то прошу добавить в настройки Вашего приложения возможность выбрать все варианты браузеров одним "кликом".

**Comment by somsern** [comment]
Yes. Excuse me. Used a slang word. After clearing the browser, the User agent settings return to the basic settings. Mozilla Firefox browser

**Comment by neroux** [comment]
Which Firefox version exactly? What is the "sync" settng set to?

CCleaner probably wipes too much and removes the configuration settings.

**Comment by somsern** [comment]
Firefox Version 64.  No synchronization is required. Mistranslation.
Until the last update, the user agent worked correctly. The browser was the same, everything worked fine. Previously, after cleaning, the settings did not break. 
Hardly a mistake. Because the reason is not clear.So wish. Can I change the initial settings of the user agent? It is inconvenient to constantly change the settings.

**Comment by neroux** [comment]
Without further details I am afraid I cant tell what is going on. My best guess is CCleaner regularly wipes the configuration settings. For Firefox 64 (without synced settings) these should be in `browser-extension-data\{b43b974b-1d3a-4232-b226-eaa2ac6ebb69}\storage.js` in your profile directory.

**Comment by somsern** [comment]
Где находятся файлы приложения я нашел. Даже нашел грубый вариант как их открыть. Через Notepad и Njtepad++ ) Но сохранить изменения не смог. Я вообще не программист. Интуитивный подход)))

**Comment by somsern** [comment]
Where are the application files I found. Even found a rough way to open them. Through Notepad and Notepad++) but could not save the changes. I'm not a programmer at all. Intuitive approach)))

**Comment by neroux** [comment]
The code should be in `{b43b974b-1d3a-4232-b226-eaa2ac6ebb69}.xpi` in the extensions directory of your profile.

**Comment by somsern** [comment]
it is difficult to explain without knowing the language. thank you for your time.

**Comment by neroux** [comment]
Maybe @tarampampam could jump in, he is a Russian native speaker.

**Comment by somsern** [comment]
могу я с ним поговорить?)

**Comment by somsern** [comment]
can I speak with him?)

**Comment by neroux** [comment]
I tagged him for that purpose :)

Maybe there is also some contact information at https://habr.com/users/paramtamtam/
