### ISSUE TITLE
[Solved] Settings lost when exiting Firefox

### ISSUE THREAD

**Issue by zynexiz** [tarampampam/random-user-agent#90]
The settings isn't preserved after I exit Firefox. When restarting Firefox, the User Agent section is reverted to the default settings (Chrome).

![screenshot_20190105_131709](https://user-images.githubusercontent.com/22789493/50724377-54096300-10e4-11e9-9fdd-c7356dacf5fa.png)

Not sure if this is due to the fact that I clear out all data from Firefox when i exit, or if some other plugin prevent the settings to get saved. I have uBlock Origin and Privacy Setting installed to. The settings for those plugins get saved over sessions though, so it souldn't have anything to do with the fact that i clear out the data. I have the same issue on FF for Android to.

I use Firefox v64 64-bit version on Linux (KaOS), but this error existed on prev versions to.

**Comment by zynexiz** [comment]
Browsing thru the closed bugs, I found a comment about sync between browser. Disabling it seems to do the trick :)

**Comment by neroux** [comment]
You probably came across #56. Can you check if the problem disappears when setting `webextensions.storage.sync.enabled` to true?

**Comment by zynexiz** [comment]
webextensions.storage.sync.enabled is already set to true here.

**Comment by neroux** [comment]
I'll have a look at it then. Can you check in the meantime if the extension debug window points to any errors in your case, when the sync is enabled?

**Comment by neroux** [comment]
I just tried with a fresh browser profile and I am afraid I could not reproduce it. Could you also run a test with such a new profile?

**Comment by zynexiz** [comment]
When i enabled sync it got this error in the debug console.

```
error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:311:5
createSourceActors/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/TabSources.js:399:21
Line: 311, column: 5 main.js:1168
```

**Comment by neroux** [comment]
Was this from the extension's console? That must be either from a different extension or an unrelated error, there are no such files in RUA.

What happens when you try it with a fresh browser profile?

**Comment by neroux** [comment]
Alright, thanks, so it is the purging of the browser data?! And it work when you save the data locally? Probably not much the extension can do in this case. Maybe defaulting to local storage would be a good idea.

Also, thanks for the review, as I mentioned in the response if you could reconsider - under the changed circumstances now - five stars it would be a nice touch :)

**Comment by zynexiz** [comment]
Got a new screen dump for you (with english this time) :)

![screenshot_20190105_152929](https://user-images.githubusercontent.com/22789493/50725513-8fad2880-10f6-11e9-9e0f-2b797fbd1a3f.png)

**Comment by zynexiz** [comment]
Updated my rewiev, and added the solution to why this happens if others run into it :)

**Comment by neroux** [comment]
I can partially reproduce it but not consistently I am afraid, so I cant say which setting exactly deletes the configuration. Switching the sync's default shouldnt be an issue.

As for more profiles, which ones would you have in mind? Even though it wouldnt be automatic, you can always create a custom list.

**Comment by AngelicStripes263** [comment]
I was about to open an issue when I saw this thread, I'm having identical issues and have a similar setup as OP. All my other privacy-focused addons work fine with my FF setup (clears browser data on close, but all addons retain settings except this one.)

**Comment by zynexiz** [comment]
Bit odd. If I enable sync, the settings always get defaulted here. And if I don't delete browser history, the settings will be intact. Maybe the problem lays at Firefox on this one?

**Comment by zynexiz** [comment]
@AngelicStripes263 Same here. I use uBlock Origin and Privacy Settings, and those settings is intact. Although, they don't have a sync between browser. Think the problem lays there. Not sure how FF handles data sync between browsers.

**Comment by AngelicStripes263** [comment]
@neroux I do not have Firefox Sync logged in/setup on this device. I did some testing and when `webextensions.storage.sync.enabled` is set to `false` it retains all settings, changing it back to `true` makes it ignore any changes upon browser restart.

**Comment by neroux** [comment]
I wasnt referring to Firefox Sync itself but to the sync feature of the extension. I assume right now you have it enabled and you shouldnt experience the issue if you disable it, right?

**Comment by AngelicStripes263** [comment]
The extension sync feature was always turned off.

![off](https://user-images.githubusercontent.com/46413668/50742683-a0d06500-11dc-11e9-8d62-ad3fe77d8641.PNG)

**Comment by neroux** [comment]
Thanks, so the issue is different from @zynexiz's and might be more related to #89.

Unfortunately without being able to proper reproduce it it will be a bit difficult to address it. Have you tried whether you can reproduce it with a fresh profile as well?

For now I can only invite you run the extension through the extension debugger yourself or, alternatively, package a profile where you can reproduce it and send it over to me.

You are not running any additional cleaner software, such as in the referenced thread, are you?
