### ISSUE TITLE
Most used/common user agents

### ISSUE THREAD

**Issue by jackTaw88** [tarampampam/random-user-agent#94]
It would be great if we have an option to use most common user agent. So if we enable that feature firefox will use most common user agents.

For example most common user agents are:
- OS
http://gs.statcounter.com/windows-version-market-share/desktop/worldwide/2018
Windows 10

- Browser
http://gs.statcounter.com/browser-market-share/desktop/worldwide/2018
Chrome

The extension will hardcode include 10 UA and it will be used by user who enable that feature.

Or it would be great for me, if you give me a trusted (no one is trusted but anyway :) ) web site where I can find most common UA strings...

Thanks

**Comment by neroux** [comment]
I am afraid I am not quite sure about the question. You simply select the desired user agents from the list and RUA will generate the necessary user agent.

**Comment by neroux** [comment]
No response, closing.
