### ISSUE TITLE
[Bug] YouTube Breaks With Random User-Agent

### ISSUE THREAD

**Issue by zero77** [tarampampam/random-user-agent#96]
## Describe the bug

When visiting youtube with Random User-Agent enabled there is only a white page displayed with gray outlines. But, once  Random User-Agent is disabled it works again.

### Screenshots
![Imgur](https://i.imgur.com/HdX13sW.png)

### Desktop (please complete the following information):

 - OS: [e.g. `iOS`, `Linux`, `Windows`] Ubunto 18.04
 - Browser: [e.g. `Chrome`, `Firefox`] Firefox 65
 - Version: [e.g. `67.0.3396.62 64 bit`]  2.2.7 x64
 - User Agent under which the issue appears: [e.g. `Chrome 70`, `Firefox 62`]  the default

**Comment by neroux** [comment]
Please see #41. It is an issue of Youtube, not of the extension.

**Comment by zero77** [comment]
@neroux 
Is it possible to whitelist youtube in Firefox so this stops happening.

**Comment by neroux** [comment]
Sure, simply add the site to your whitelist in the extension's options.

**Comment by zero77** [comment]
I missed that, thanks.
