### ISSUE TITLE
In the Google Chrome browser, the program spontaneously disconnects

### ISSUE THREAD

**Issue by DAWspo** [tarampampam/random-user-agent#97]
## Describe the bug

> A clear and concise description of what the bug is.

### Expected behaviour:

> Tell us what should happen.

### Actual behaviour:

> Tell us what happens instead.

### Steps to reproduce the behavior:

 2. Click on '...'
 3. See error

### Screenshots

> If applicable, add screenshots to help explain your problem.
>
> Google Chrome: **Menu → Settings → More tools → Extensions → Developer mode (check) → Random User-Agent → Background Page** → [Press **PrtScn**]

### Desktop (please complete the following information):

 - OS: [e.g. `iOS`, `Linux`, `Windows`]
 - Browser: [e.g. `Chrome`, `Firefox`]
 - Version: [e.g. `67.0.3396.62 64 bit`]
 - User Agent under which the issue appears: [e.g. `Chrome 70`, `Firefox 62`]

## Additional context

> Add any other context about the problem here.

**Comment by neroux** [comment]
Nothing provided expect for a title. Closing.
