### ISSUE TITLE
User-agent leaked when viewing page source in Firefox

### ISSUE THREAD

**Issue by Mldx** [tarampampam/random-user-agent#99]
## Describe the bug

Your user-agent is leaked when viewing the source of a page using view-source:URL in Firefox

### Steps to reproduce the behavior:

 1. View the source of any page in Firefox using 
>view-source:URL

An example could be
>view-source:https://google.com

### Desktop:

 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 66.0b10 (64-bit)
 - User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

## Additional context

The user-agent does not leak using Chrome (Version 72.0.3626.119 (Official Build) (64-bit))

**Comment by neroux** [comment]
Where? You need to post a screenshot. The user agent is not automatically part of a site.

**Comment by Mldx** [comment]
It's sent with as a request header. I'll give you an example.

This is a request to http://127.0.0.1/ (The user agent isn't leaked)
![1](https://user-images.githubusercontent.com/12830098/53366385-b98b0a80-3943-11e9-9b35-c3364b4ef8a4.PNG)

This is a request to http://127.0.0.1/, but here I use view-source in the URL (The user agent is leaked)
![2](https://user-images.githubusercontent.com/12830098/53366426-dc1d2380-3943-11e9-8828-7e3c10b595c2.PNG)

Make sure the page isn't cached when viewing the source of the page.

**Comment by neroux** [comment]
This is not **any** page but something on your local machine.

**Comment by Mldx** [comment]
I tested this on multiple sites, it leaks on all sites I've tested it on.

I just used a local web server as an example.

**Comment by neroux** [comment]
Which sites? Again, post screenshots.

**Comment by neroux** [comment]
Your screenshots do not show anything out of the ordinary. They simply show the currently selected user agent.

**Comment by Mldx** [comment]
This time I tried with example.org

This is a request without view-source (Using a random user agent)
![1_2](https://user-images.githubusercontent.com/12830098/53378665-b2292880-3966-11e9-9a57-e074152efac4.PNG)

And here I have a request to the same site using view-source (My real user agent is leaked, using the same extension settings as before)
![2_2](https://user-images.githubusercontent.com/12830098/53378681-c836e900-3966-11e9-8c5e-3b0cc949e5e8.PNG)

The screenshots shows the user-agent that is sent with the request I am making to the webserver. The user agent on the second screenshot is my real user agent which isn't supposed to be sent, even though the extension is enabled and set to use another user agent.

**Comment by neroux** [comment]
So you are referring to the request header(!) visible in the developer tools and not what is shown on the page. That is what you had to clarify.

I cant comment on or confirm this yet but will have a look and will get back to you.

**Comment by neroux** [comment]
I seem to be able to confirm the issue, however I am afraid there might be little the extension can do in this regard.

Firefox does not appear to allow extensions to run in a view-source context. See https://stackoverflow.com/a/49106105
